using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Abstractions;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Branch update model.
    /// </summary>
    [MessagePack.MessagePackObject()]
    public sealed class BranchModelUpdate : IModelIntIdentifier, IBranchModel
    {
        /// <inheritdoc/>
        [MessagePack.Key(0)]
        public int Id { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(1)]
        [Required()]
        [StringLength(45, MinimumLength = 1)]
        public string Name { get; init; } = string.Empty;

        /// <inheritdoc/>
        [MessagePack.Key(2)]
        [StringLength(45)]
        public string? City { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(3)]
        [StringLength(255)]
        public string? Address { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(4)]
        [StringLength(45)]
        public string? Phone { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(5)]
        [StringLength(255)]
        public string? Email { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(6)]
        [StringLength(45)]
        public string? PostalCode { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(7)]
        [StringLength(45)]
        public string? Region { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(8)]
        [StringLength(255)]
        public string? WebSite { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(9)]
        [StringLength(255)]
        public string? Info { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(10)]
        [StringLength(45)]
        public string? TimeZone { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(11)]
        public bool IsEnabled { get; init; }

        /// <inheritdoc/>
        [MessagePack.Key(12)]
        public bool IsDeleted { get; init; }

        ///this member is present only to saticfy the interface
        ///the value is autogenerated upon entity creation and never modified
        /// <inheritdoc/>        
        [System.Text.Json.Serialization.JsonIgnore()]
        [MessagePack.IgnoreMember()]
        public Guid Guid { get; } = Guid.Empty;
    }
}
