using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Reservation host added event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Expired", nameof(Resources.RESERVATION_HOST_EXPIRED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Host reservation expired event", nameof(Resources.RESERVATION_HOST_EXPIRED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class ReservationHostExpiredEventMessage : ReservationEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ReservationHostExpiredEventMessage() { }

        /// <summary>
        /// Host id.
        /// </summary>
        [MessagePack.Key(2)]
        public int HostId
        {
            get;init;
        }
    }
}
