using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User added event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Added", nameof(Resources.RESERVATION_USER_ADDED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("User added", nameof(Resources.RESERVATION_USER_ADDED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class ReservationUserAddedEventMessage : ReservationEventMessageBase
    {
        /// <summary>
        /// User id.
        /// </summary>
        [MessagePack.Key(2)]
        public int UserId { get; init; }
    }
}
