using MessagePack;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Reservation created event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Cancelled", nameof(Resources.RESERVATION_CANCELLED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Reservation cancelled event", nameof(Resources.RESERVATION_CANCELLED_EVENT_DESCRIPTION))]
    [MessagePackObject()]
    public sealed class ReservationCancelledEventMessage : ReservationEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ReservationCancelledEventMessage() : base()
        { }
    }
}
