using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User removed event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Removed", nameof(Resources.RESERVATION_USER_REMOVED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("User removed", nameof(Resources.RESERVATION_USER_REMOVED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class ReservationUserRemovedEventMessage : ReservationEventMessageBase
    {
        /// <summary>
        /// User id.
        /// </summary>
        [MessagePack.Key(2)]
        public int UserId { get; init; }
    }
}
