using MessagePack;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Reservation created event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Completed", nameof(Resources.RESERVATION_COMPLETED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Reservation completed event", nameof(Resources.RESERVATION_COMPLETED_EVENT_DESCRIPTION))]
    [MessagePackObject()]
    public sealed class ReservationCompletedEventMessage : ReservationEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ReservationCompletedEventMessage():base() { }
    }
}
