using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Reservation created event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Created", nameof(Resources.RESERVATION_CREATED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Reservation created", nameof(Resources.RESERVATION_CREATED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class ReservationCreatedEventMessage : ReservationEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ReservationCreatedEventMessage() : base()
        { }
    }
}
