using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Reservation expired event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Expired", nameof(Resources.RESERVATION_EXPIRED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Reservation expired", nameof(Resources.RESERVATION_EXPIRED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class ReservationExpiredEventMessage : ReservationEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ReservationExpiredEventMessage() : base() { }
    }
}
