using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Reservation activated event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Activated", nameof(Resources.RESERVATION_ACTIVATED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Reservation activated event", nameof(Resources.RESERVATION_ACTIVATED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class ReservationActivatedEventMessage : ReservationEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ReservationActivatedEventMessage() : base() { }
    }
}
