using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User created event message.
    /// </summary>
    [MessagePack.MessagePackObject]
    [System.ComponentModel.DataAnnotations.Name("User created", nameof(Resources.USER_CREATED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates user account creation", nameof(Resources.USER_CREATED_EVENT_DESCRIPTION))]
    public sealed class UserCreatedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserCreatedEventMessage() : base()
        { }
    }
}
