using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User enable negative balance changed event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Negative balance change", nameof(Resources.USER_NEGATIVE_BALANCE_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates negative balance change", nameof(Resources.USER_NEGATIVE_BALANCE_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserNegativeBalanceEnabledEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserNegativeBalanceEnabledEventMessage() : base()
        { }

        /// <summary>
        /// Gets if negative balance allowed for user.
        /// </summary>
        [Key(2)]
        public bool? IsEnabled
        {
            get; init;
        }
    }
}
