using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User balance changed event message.
    /// </summary>
    [MessagePack.MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Balance changed", nameof(Resources.USER_BALANCE_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates balance change", nameof(Resources.USER_BALANCE_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserBalanceChangedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserBalanceChangedEventMessage() : base()
        { }

        /// <summary>
        /// Balance.
        /// </summary>
        [MessagePack.Key(2)]
        public decimal Balance { get; init; }

        /// <summary>
        /// Deposit balance.
        /// </summary>
        [MessagePack.Key(3)]
        public decimal Deposits { get; init; }

        /// <summary>
        /// Time balance.
        /// </summary>
        [MessagePack.Key(4)]
        public double? Time
        {
            get;init;
        }

        /// <summary>
        /// Credited time balance.
        /// </summary>
        [MessagePack.Key(5)]
        public double? CreditedTime { get; init;}

        /// <summary>
        /// Points balance.
        /// </summary>
        [MessagePack.Key(6)]
        public int Points { get; init;}

        /// <summary>
        /// Current outstanding amount.
        /// </summary>
        [MessagePack.Key(7)]
        public decimal Outstanding {  get; init; }
    }
}
