using Gizmo.Web.Api.Models;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User note added event message.
    /// </summary>
    [MessagePack.MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Note added", nameof(Resources.USER_NOTE_ADDED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates that user note has been added", nameof(Resources.USER_NOTE_ADDED_EVENT_DESCRIPTION))]
    public sealed class UserNoteAddedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// User note id.
        /// </summary>
        [MessagePack.Key(2)]
        public required int UserNoteId { get; init; }

        /// <summary>
        /// Note severity.
        /// </summary>
        [MessagePack.Key(3)]
        public required NoteSeverity Severity { get; init; }
    }
}
