using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User usage session event message.
    /// </summary>
    [MessagePack.MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Usage session change", nameof(Resources.USER_USAGE_SESSION_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates usage session change", nameof(Resources.USER_USAGE_SESSION_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserUsageSessionUsageChangedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserUsageSessionUsageChangedEventMessage() : base()
        { }

        /// <summary>
        /// Gets usage session id.
        /// </summary>
        [MessagePack.Key(2)]
        public int UsageSessionId
        {
            get; init;
        }

        /// <summary>
        /// Gets current usage.
        /// </summary>
        [MessagePack.Key(3)]
        public UsageSessionUsage CurrentUsage
        {
            get; init;
        } = null!;
    }
}
