using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User picture changed event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Picture change", nameof(Resources.USER_PICTURE_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates picture change", nameof(Resources.USER_PICTURE_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserPictureChangedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserPictureChangedEventMessage() : base()
        { }
    }
}
