using Gizmo.Web.Api.Models.Autogenerated;
using Gizmo.Web.Api.Models;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User billing options change event.
    /// </summary>
    [MessagePack.MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Billing options change", nameof(Resources.USER_BALANCE_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates billing options change", nameof(Resources.USER_BALANCE_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserBillingOptionsChangedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Current options.
        /// </summary>
        [MessagePack.Key(2)]
        public BillingOption? Options { get;init; }
    }
}
