using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User smart card change event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Smart card change", nameof(Resources.USER_SMART_CARD_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates smart card change", nameof(Resources.USER_SMART_CARD_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserSmartCardChangeEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserSmartCardChangeEventMessage() : base()
        { }

        /// <summary>
        /// Smart card uid.
        /// </summary>
        [MessagePack.Key(2)]
        public string? SmartCardUid { get; init; }
    }
}
