using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User renamed event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Rename", nameof(Resources.USER_RENAME_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates user rename", nameof(Resources.USER_RENAME_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserRenamedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserRenamedEventMessage() : base()
        { }

        /// <summary>
        /// Gets new user name.
        /// </summary>
        [Key(2)]
        public required string NewUserName
        {
            get;init;
        }

        /// <summary>
        /// Gets old user name.
        /// </summary>
        [Key(3)]
        public required string OldUserName
        {
            get;init;
        }
    }
}
