using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User password changed event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Password change", nameof(Resources.USER_PASSWORD_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates password change", nameof(Resources.USER_PASSWORD_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserPasswordChangedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserPasswordChangedEventMessage() : base()
        { }
    }
}
