using System;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User enabled change event message.
    /// </summary>
    [MessagePack.MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Enabled", nameof(Resources.USER_ENABLED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates enablement of an user", nameof(Resources.USER_ENABLED_EVENT_DESCRIPTION))]
    public sealed class UserEnabledChangedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserEnabledChangedEventMessage() : base()
        { }

        /// <summary>
        /// Gets if user is disabled.
        /// </summary>
        [MessagePack.Key(2)]
        public bool Disabled
        {
            get;
            init;
        }

        /// <summary>
        /// Gets enable date.
        /// </summary>
        [MessagePack.Key(3)]
        public DateTime? EnableDate
        {
            get;
            init;
        }

        /// <summary>
        /// Gets disabled date.
        /// </summary>
        [MessagePack.Key(4)]
        public DateTime? DisabledDate
        {
            get;
            init;
        }

        /// <summary>
        /// Gets disable reason.
        /// </summary>
        [MessagePack.Key(5)]
        public string? Reason
        {
            get;
            init;
        }
    }
}
