using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User email changed event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Email change", nameof(Resources.USER_EMAIL_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates email change", nameof(Resources.USER_EMAIL_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserEmailChangedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserEmailChangedEventMessage() : base()
        { }

        /// <summary>
        /// Gets new email value.
        /// </summary>
        [Key(2)]
        public required string? NewEmail
        {
            get;
            init;
        }

        /// <summary>
        /// Gets old email value.
        /// </summary>
        [Key(3)]
        public required string? OldEmail
        {
            get;
            init;
        }
    }
}
