using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User balance close event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Balance close", nameof(Resources.USER_BALANCE_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates balance close", nameof(Resources.USER_BALANCE_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserBalanceCloseEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserBalanceCloseEventMessage() : base()
        { }
    }
}
