using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User group changed event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("User group change", nameof(Resources.USER_USER_GROUP_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates user group change", nameof(Resources.USER_USER_GROUP_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserGroupChangedEventMessage : UserEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserGroupChangedEventMessage() : base()
        { }

        /// <summary>
        /// Gets new user group id.
        /// </summary>
        [Key(2)]
        public required int NewUserGroupId
        {
            get; init;
        }

        /// <summary>
        /// Gets old user group id.
        /// </summary>
        [Key(3)]
        public required int OldUserGroupId
        {
            get; init;
        }
    }
}
