using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Promotion create model.
    /// </summary>
    [MessagePack.MessagePackObject()]
    public sealed class PromotionCreateModel : IWebApiModel
    {
        /// <summary>
        /// Promotion name.
        /// </summary>
        [MessagePack.Key(0)]
        [Required]
        [StringLength(45)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// Promotion description.
        /// </summary>
        [MessagePack.Key(1)]
        [StringLength(255)]
        public string? Description { get; set; }

        /// <summary>
        /// Promotion type.
        /// </summary>
        [MessagePack.Key(2)]
        public PromotionTypes Type { get; set; }

        /// <summary>
        /// Discount or discount group id.
        /// </summary>
        /// <remarks>
        /// This value depends on <see cref="Type"/>.
        /// </remarks>
        [MessagePack.Key(3)]
        public int DiscountId { get; set; }

        /// <summary>
        /// Indicates that promotion is disabled.
        /// </summary>
        [MessagePack.Key(4)]
        [DefaultValue(false)]
        public bool IsDisabled { get; set; }

        /// <summary>
        /// Promotion period.
        /// </summary>
        [MessagePack.Key(5)]
        public PeriodModel Period { get; set; } = new();

        /// <summary>
        /// Promotion limits.
        /// </summary>
        [MessagePack.Key(6)]
        public IEnumerable<PromotionLimitModel> Limits { get; set; } = Enumerable.Empty<PromotionLimitModel>();

        /// <summary>
        /// Promotion code type.
        /// </summary>
        [MessagePack.Key(7)]
        public PromotionCodeType CodeType { get; set; } = PromotionCodeType.Public;

        /// <summary>
        /// Code prefix.
        /// </summary>
        /// <remarks>
        /// This value will only be used in case of <see cref="PromotionCodeType.Restricted"/>.<br></br>
        /// Leaving null or setting to zero will default to empty string.
        /// </remarks>
        [MessagePack.Key(8)]
        [StringLength(100)] // max 100 chars for prefix, 155 will be left for autogenerated part
        public string? CodePrefix { get; set; }

        /// <summary>
        /// Code length.
        /// </summary>
        /// <remarks>
        /// This value will only be used in case of <see cref="PromotionCodeType.Restricted"/>.<br></br>
        /// Leaving null or setting to zero will default to 5 characters.
        /// </remarks>
        [MessagePack.Key(9)]
        [DefaultValue(5)]
        [Range(1, 155)]
        public int? CodeLength { get; set; }

        /// <summary>
        /// Promo code count.
        /// </summary>
        /// <remarks>
        /// This value will only be used in case of <see cref="PromotionCodeType.Restricted"/>.<br></br>
        /// Leaving null or setting to zero will default to 1 code.
        /// </remarks>
        [MessagePack.Key(10)]
        [DefaultValue(1)]
        [Range(1, int.MaxValue)]
        public int? CodeCount { get; set; }

        /// <summary>
        /// Code character set.
        /// </summary>
        /// <remarks>
        /// This value will only be used in case of <see cref="PromotionCodeType.Restricted"/>.<br></br>
        /// Leaving null will default to <see cref="CharSetType.UppercaseLetters"/>.
        /// </remarks>
        [MessagePack.Key(11)]
        [DefaultValue(CharSetType.UppercaseLetters)]
        public CharSetType? CodeCharSetType { get; set; }

        /// <summary>
        /// Branches.
        /// </summary>
        [MessagePack.Key(12)]
        public IEnumerable<BranchReferenceModelUpdate> Branches { get; set; } = Enumerable.Empty<BranchReferenceModelUpdate>();
    }
}
