using Gizmo.Web.Api.Models;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Host layout created event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Instance authorization changed", nameof(Resources.INSTANCE_AUTHORIZATION_CHANGED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Instance authorization changed event", nameof(Resources.INSTANCE_AUTHORIZATION_CHANGED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class InstanceAuthorizationChangedEventMessage : InstanceEventMessageBase
    {
    }
}
