using Gizmo.Web.Api.Models;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Host layout created event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Instance authentication changed", nameof(Resources.INSTANCE_AUTHENTICATION_CHANGED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Instance authentication changed event", nameof(Resources.INSTANCE_AUTHENTICATION_CHANGED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class InstanceAuthenticationChangedEventMessage : InstanceEventMessageBase
    {
    }
}
