using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// What triggered an achievement ladder level transition.
    /// Value-identical copy of the storage enum.
    /// </summary>
    public enum AchievementLadderEventTrigger
    {
        /// <summary>
        /// Live promotion within the current period.
        /// </summary>
        [Name("Live", nameof(Resources.ACHIEVEMENT_LADDER_EVENT_TRIGGER_LIVE_NAME))]
        Live = 0,

        /// <summary>
        /// Period-boundary settle — the only place demotion happens.
        /// </summary>
        [Name("Settle", nameof(Resources.ACHIEVEMENT_LADDER_EVENT_TRIGGER_SETTLE_NAME))]
        Settle = 1,

        /// <summary>
        /// Operator action.
        /// </summary>
        [Name("Operator", nameof(Resources.ACHIEVEMENT_LADDER_EVENT_TRIGGER_OPERATOR_NAME))]
        Operator = 2,
    }
}
