using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Achievement challenge option flags.
    /// </summary>
    [Flags]
    public enum AchievementChallengeOptionType
    {
        /// <summary>
        /// No options set.
        /// </summary>
        [Name("None", nameof(Resources.ACHIEVEMENT_CHALLENGE_OPTION_NONE_NAME))]
        None = 0,

        /// <summary>
        /// The challenge is not displayed to end users in client interfaces.
        /// Presentation only — a hidden challenge still evaluates and grants.
        /// </summary>
        [Name("Hidden", nameof(Resources.ACHIEVEMENT_CHALLENGE_OPTION_HIDDEN_NAME))]
        Hidden = 1,
    }
}
