using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Achievement ladder scoring modes.
    /// </summary>
    public enum AchievementLadderMode
    {
        /// <summary>
        /// Achievements award points per completion; levels are reached by point thresholds.
        /// </summary>
        [Name("Points", nameof(Resources.ACHIEVEMENT_LADDER_MODE_POINTS_NAME))]
        Points = 0,

        /// <summary>
        /// Levels list required achievements; the highest satisfied level wins.
        /// </summary>
        [Name("Requirements", nameof(Resources.ACHIEVEMENT_LADDER_MODE_REQUIREMENTS_NAME))]
        Requirements = 1,
    }
}
