using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Achievement option flags.
    /// </summary>
    [Flags]
    public enum AchievementOptionType
    {
        /// <summary>
        /// No options set.
        /// </summary>
        [Name("None", nameof(Resources.ACHIEVEMENT_OPTION_NONE_NAME))]
        None = 0,

        /// <summary>
        /// The achievement is not displayed to end users in client interfaces.
        /// Presentation only — a hidden achievement still evaluates and completes.
        /// </summary>
        [Name("Hidden", nameof(Resources.ACHIEVEMENT_OPTION_HIDDEN_NAME))]
        Hidden = 1,
    }
}
