using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Achievement ladder option flags.
    /// </summary>
    [Flags]
    public enum AchievementLadderOptionType
    {
        /// <summary>
        /// No options set.
        /// </summary>
        [Name("None", nameof(Resources.ACHIEVEMENT_LADDER_OPTION_NONE_NAME))]
        None = 0,

        /// <summary>
        /// Promotions are applied only at the period boundary settle instead of instantly —
        /// a period's activity decides the level held through the following period.
        /// </summary>
        [Name("Promote on settle only", nameof(Resources.ACHIEVEMENT_LADDER_OPTION_PROMOTE_ON_SETTLE_ONLY_NAME))]
        PromoteOnSettleOnly = 1,
    }
}
