using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Achievement challenge reward option flags.
    /// </summary>
    [Flags]
    public enum AchievementChallengeRewardOptionType
    {
        /// <summary>
        /// No options set.
        /// </summary>
        [Name("None", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_OPTION_NONE_NAME))]
        None = 0,

        /// <summary>
        /// Force manual (operator) fulfillment for a reward that would otherwise grant
        /// automatically. Redundant on product rewards, which always require fulfillment.
        /// </summary>
        [Name("Force claim", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_OPTION_FORCE_CLAIM_NAME))]
        ForceClaim = 1,
    }
}
