using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Lifecycle status of an earned challenge reward.
    /// </summary>
    /// <remarks>
    /// The two undelivered statuses say who the reward is waiting on, and the two delivered
    /// ones say which path delivered it — both distinctions are recorded when the row moves,
    /// never inferred from the processing operator, which is an audit stamp.
    /// </remarks>
    public enum AchievementChallengeRewardStatus
    {
        /// <summary>
        /// Awaiting automatic delivery; a lingering value indicates a retryable failure.
        /// </summary>
        [Name("Pending", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_STATUS_PENDING_NAME))]
        Pending = 0,

        /// <summary>
        /// Awaiting operator fulfillment — physical products and force-claim rewards.
        /// </summary>
        [Name("Awaiting claim", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_STATUS_AWAITING_CLAIM_NAME))]
        AwaitingClaim = 1,

        /// <summary>
        /// Delivered automatically by the system.
        /// </summary>
        [Name("Delivered", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_STATUS_DELIVERED_NAME))]
        Delivered = 2,

        /// <summary>
        /// Terminally declined by an operator or the user; nothing was delivered.
        /// </summary>
        [Name("Declined", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_STATUS_DECLINED_NAME))]
        Declined = 3,

        /// <summary>
        /// Claimed — handed over by an operator, or claimed by the user themselves when the
        /// reward is not a physical one.
        /// </summary>
        [Name("Claimed", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_STATUS_CLAIMED_NAME))]
        Claimed = 4,
    }
}
