using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Grant lifecycle status of an earned challenge reward.
    /// </summary>
    public enum AchievementChallengeRewardStatus
    {
        /// <summary>
        /// Awaiting automatic grant; a lingering value indicates a retryable failure.
        /// </summary>
        [Name("Pending", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_STATUS_PENDING_NAME))]
        Pending = 0,

        /// <summary>
        /// Awaiting operator fulfillment — physical products and force-claim rewards.
        /// </summary>
        [Name("Awaiting claim", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_STATUS_AWAITING_CLAIM_NAME))]
        AwaitingClaim = 1,

        /// <summary>
        /// Delivered.
        /// </summary>
        [Name("Granted", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_STATUS_GRANTED_NAME))]
        Granted = 2,

        /// <summary>
        /// Terminally declined by an operator or the user; nothing was delivered.
        /// </summary>
        [Name("Declined", nameof(Resources.ACHIEVEMENT_CHALLENGE_REWARD_STATUS_DECLINED_NAME))]
        Declined = 3,
    }
}
