using System.ComponentModel.DataAnnotations;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Authorization result codes.
    /// </summary>
    public enum AuthorizationResultCodes
    {
        /// <summary>
        /// Success.
        /// </summary>
        [Name("Success", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_SUCCESS_NAME))]
        [ExtendedDescription("Authorization successful", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_SUCCESS_DESCRIPTION))]
        Success,

        /// <summary>
        /// Unauthorized.
        /// </summary>
        [Name("Unauthorized", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_UNAUTHORIZED_NAME))]
        [ExtendedDescription("Unauthorized", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_UNAUTHORIZED_DESCRIPTION))]
        Unauthorized,

        /// <summary>
        /// Expired token.
        /// </summary>
        [Name("Token expired", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_TOKEN_EXPIRED_NAME))]
        [ExtendedDescription("Failed due to a expired token", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_TOKEN_EXPIRED_DESCRIPTION))]
        TokenExpired,

        /// <summary>
        /// Invalid instance id.
        /// </summary>
        [Name("Invalid id", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_INVALID_ID_NAME))]
        [ExtendedDescription("Failed due to an invalid instance id", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_INVALID_ID_DESCRIPTION))]
        InvalidId,

        /// <summary>
        /// Network error.
        /// </summary>
        [Name("Network error", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_NETWORK_ERROR_NAME))]
        [ExtendedDescription("Failed due to an network error", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_NETWORK_ERROR_DESCRIPTION))]
        NetworkError,

        /// <summary>
        /// General error.
        /// </summary>
        [Name("Error", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_NETWORK_ERROR_NAME))]
        [ExtendedDescription("Failed due to an error", nameof(Autogenerated.Resources.AUTHORIZATION_RESULT_NETWORK_ERROR_DESCRIPTION))]
        Error,
    }
}
