using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Authentication result codes.
    /// </summary>
    public enum AuthenticationResultCodes
    {
        /// <summary>
        /// Success.
        /// </summary>
        [Name("Success", nameof(Resources.AUTHENTICATION_RESULT_SUCCESS_NAME))]
        [ExtendedDescription("Authentication successful", nameof(Resources.AUTHENTICATION_RESULT_SUCCESS_DESCRIPTION))]
        Success = 0,

        /// <summary>
        /// Unauthorized.
        /// </summary>
        [Name("Unauthorized", nameof(Resources.AUTHENTICATION_RESULT_UNAUTHORIZED_NAME))]
        [ExtendedDescription("Unauthorized", nameof(Resources.AUTHENTICATION_RESULT_UNAUTHORIZED_DESCRIPTION))]
        Unauthorized = 1,

        /// <summary>
        /// Network error.
        /// </summary>
        [Name("Network error", nameof(Resources.AUTHENTICATION_RESULT_NETWORK_ERROR_NAME))]
        [ExtendedDescription("Failed due to a network error", nameof(Resources.AUTHENTICATION_RESULT_NETWORK_ERROR_DESCRIPTION))]
        NetworkError = 2,

        /// <summary>
        /// General error.
        /// </summary>
        [Name("Error", nameof(Resources.AUTHENTICATION_RESULT_ERROR_NAME))]
        [ExtendedDescription("Failed due to an error", nameof(Resources.AUTHENTICATION_RESULT_ERROR_DESCRIPTION))]
        Error = 3,
    }
}
