using System;
using System.ComponentModel.DataAnnotations;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Authorization warnings.
    /// </summary>
    [Flags()]
    public enum AuthorizationWarnings
    {
        /// <summary>
        /// No warnings.
        /// </summary>
        [Name("None", nameof(Autogenerated.Resources.AUTHORIZATION_WARNINGS_NONE_NAME))]
        [ExtendedDescription("None", nameof(Autogenerated.Resources.AUTHORIZATION_WARNINGS_NONE_DESCRIPTION))]
        None = 0,

        /// <summary>
        /// Payment failure.
        /// </summary>
        [Name("Payment failure", nameof(Autogenerated.Resources.AUTHORIZATION_WARNINGS_PAYMENT_FAILURE_NAME))]
        [ExtendedDescription("Payment attempt did not succeed", nameof(Autogenerated.Resources.AUTHORIZATION_WARNINGS_FUTURE_PAYMENT_DESCRIPTION))]
        PaymentFailure = 1,

        /// <summary>
        /// Future payment warning.
        /// </summary>
        [Name("Future payment warning", nameof(Autogenerated.Resources.AUTHORIZATION_WARNINGS_FUTURE_PAYMENT_NAME))]
        [ExtendedDescription("Future payments may fail due to card expiration", nameof(Autogenerated.Resources.AUTHORIZATION_WARNINGS_FUTURE_PAYMENT_DESCRIPTION))]
        FuturePaymentWarning = 2
    }
}
