using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Time billing options.
    /// </summary>
    [Flags()]
    public enum BillingOption
    {
        /// <summary>
        /// None.
        /// </summary>
        [Name("None",nameof(Resources.BILLING_OPTION_NONE_NAME))]
        None = 0,
        /// <summary>
        /// Disable time offers.
        /// </summary>

        [Name("Disable time offers", nameof(Resources.BILLING_OPTION_DISABLE_TIME_OFFER_NAME))]
        DisableTimeOffer = 1,
        /// <summary>
        /// Disable fixed time.
        /// </summary>

        [Name("Disable fixed time", nameof(Resources.BILLING_OPTION_DISABLE_FIXED_TIME_NAME))]
        DisableFixedTime = 2,

        /// <summary>
        /// Disable deposits.
        /// </summary>
        [Name("Disable deposits", nameof(Resources.BILLING_OPTION_DISABLE_DEPOSITS_NAME))]
        DisableDeposit = 4,
    }
}
