using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Calendar period presets.
    /// </summary>
    public enum CalendarPeriod
    {
        /// <summary>
        /// Calendar day.
        /// </summary>
        [Name("Day", nameof(Resources.CALENDAR_PERIOD_DAY_NAME))]
        Day = 0,

        /// <summary>
        /// Calendar week.
        /// </summary>
        [Name("Week", nameof(Resources.CALENDAR_PERIOD_WEEK_NAME))]
        Week = 1,

        /// <summary>
        /// Calendar month.
        /// </summary>
        [Name("Month", nameof(Resources.CALENDAR_PERIOD_MONTH_NAME))]
        Month = 2,

        /// <summary>
        /// Calendar quarter.
        /// </summary>
        [Name("Quarter", nameof(Resources.CALENDAR_PERIOD_QUARTER_NAME))]
        Quarter = 3,

        /// <summary>
        /// Calendar year.
        /// </summary>
        [Name("Year", nameof(Resources.CALENDAR_PERIOD_YEAR_NAME))]
        Year = 4,
    }
}
