using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Communication channel types.
    /// </summary>
    public enum CommunicationChannelTypes
    {
        /// <summary>
        /// Email.
        /// </summary>
        [CommunicationChannelGuid(CommunicationChannels.Email)]
        [Name("Email", nameof(Resources.COMMUNICATION_CHANNEL_TYPES_EMAIL))]
        Email,

        /// <summary>
        /// SMS.
        /// </summary>
        [CommunicationChannelGuid(CommunicationChannels.Sms)]
        [Name("SMS", nameof(Resources.COMMUNICATION_CHANNEL_TYPES_SMS_NAME))]
        Sms,

        /// <summary>
        /// WhatsApp.
        /// </summary>
        [CommunicationChannelGuid(CommunicationChannels.WhatsApp)]
        [Name("WhatsApp", nameof(Resources.COMMUNICATION_CHANNEL_TYPES_WHATS_APP_NAME))]
        WhatsApp,

        /// <summary>
        /// Viber.
        /// </summary>
        [CommunicationChannelGuid(CommunicationChannels.Viber)]
        [Name("Viber", nameof(Resources.COMMUNICATION_CHANNEL_TYPES_VIBER_NAME))]
        Viber,

        /// <summary>
        /// Telegram.
        /// </summary>
        [CommunicationChannelGuid(CommunicationChannels.Telegram)]
        [Name("Telegram", nameof(Resources.COMMUNICATION_CHANNEL_TYPES_TELEGRAM_NAME))]
        Telegram,

        /// <summary>
        /// Facebook messenger.
        /// </summary>
        [CommunicationChannelGuid(CommunicationChannels.FacebookMessenger)]
        [Name("Facebook messenger", nameof(Resources.COMMUNICATION_CHANNEL_TYPES_FACEBOOK_MESSENGER_NAME))]
        FacebookMessenger,

        /// <summary>
        /// Instagram direct.
        /// </summary>
        [CommunicationChannelGuid(CommunicationChannels.InstagramDirect)]
        [Name("Instagram", nameof(Resources.COMMUNICATION_CHANNEL_TYPES_INSTAGRAM_NAME))]
        InstagramDirect,

        /// <summary>
        /// Twitter dm.
        /// </summary>
        [CommunicationChannelGuid(CommunicationChannels.TwitterDm)]
        [Name("Twitter", nameof(Resources.COMMUNICATION_CHANNEL_TYPES_TWITTER_DM_NAME))]
        TwitterDm,

        /// <summary>
        /// WeChat.
        /// </summary>
        [CommunicationChannelGuid(CommunicationChannels.WeChat)]
        [Name("WeChat", nameof(Resources.COMMUNICATION_CHANNEL_TYPES_WE_CHAT_NAME))]
        WeChat
    }
}
