using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Deposit transaction types.
    /// </summary>
    public enum DepositTransactionType
    {
        /// <summary>
        /// Deposit to an account.
        /// </summary>
        [Name("Deposit", nameof(Resources.DEPOSIT_TRANSACTION_TYPE_DEPOSIT_NAME))]
        Deposit = 0,
        /// <summary>
        /// Withdraw from account.
        /// </summary>
        [Name("Withdraw", nameof(Resources.DEPOSIT_TRANSACTION_TYPE_WITHDRAW_NAME))]
        Withdraw = 1,
        /// <summary>
        /// Account charge.
        /// </summary>
        [Name("Charge", nameof(Resources.DEPOSIT_TRANSACTION_TYPE_CHARGE_NAME))]
        Charge = 2,
        /// <summary>
        /// Credit an amount to account.
        /// </summary>
        [Name("Credit", nameof(Resources.DEPOSIT_TRANSACTION_TYPE_CREDIT_NAME))]
        Credit = 3
    }
}
