using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Discount value type.
    /// </summary>
    public enum DiscountCalculationType
    {
        /// <summary>
        /// Percentage discount.
        /// </summary>
        [Name("Percentage", nameof(Resources.DISCOUNT_CALCULATION_TYPE_PERCENTAGE))]
        Percentage = 0,

        /// <summary>
        /// Fixed discount.
        /// </summary>
        [Name("Fixed", nameof(Resources.DISCOUNT_CALCULATION_TYPE_FIXED))]
        Fixed = 1,
    }
}
