using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Discount reward type enumeration.
    /// </summary>
    public enum DiscountRewardType
    {
        /// <summary>
        /// Discount.
        /// </summary>
        [Name("Discount", nameof(Resources.DISCOUNT_REWARD_TYPE_DISCOUNT))]
        Discount = 0,

        /// <summary>
        /// Bonus.
        /// </summary>
        [Name("Bonus", nameof(Resources.DISCOUNT_REWARD_TYPE_BONUS))]
        Bonus = 1,
    }
}
