using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Predefined document types for the system.
    /// </summary>
    public enum DocumentTypes
    {
        /// <summary>
        /// Delivery note.
        /// </summary>
        [Name("Delivery note", nameof(Resources.DOCUMENT_TYPES_DELIVERY_NOTE))]
        DeliveryNote = -1,
        /// <summary>
        /// Dispatch note.
        /// </summary>
        [Name("Dispatch note", nameof(Resources.DOCUMENT_TYPES_DISPATCH_NOTE))]
        DispatchNote = -2,
        /// <summary>
        /// Stock take report.
        /// </summary>
        [Name("Stock take report", nameof(Resources.DOCUMENT_TYPES_STOCK_TAKE_REPORT))]
        StockTakeReport = -3,
        /// <summary>
        /// Write-off report.
        /// </summary>
        [Name("Write-off report", nameof(Resources.DOCUMENT_TYPES_WRITE_OFF_REPORT))]
        WriteOffReport = -4,
        /// <summary>
        /// Consignment note.
        /// </summary>
        [Name("Consignment note", nameof(Resources.DOCUMENT_TYPES_CONSIGNMENT_NOTE))]
        ConsignmentNote = -5,
        /// <summary>
        /// Invoice.
        /// </summary>
        [Name("Invoice", nameof(Resources.DOCUMENT_TYPES_INVOICE))]
        Invoice = -6,
        /// <summary>
        /// Work order.
        /// </summary>
        [Name("Work order", nameof(Resources.DOCUMENT_TYPES_WORK_ORDER))]
        WorkOrder = -7,
    }
}
