using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Entity event type.
    /// </summary>
    public enum EntityEventType
    {
        /// <summary>
        /// Added.
        /// </summary>
        [Name("Added", nameof(Resources.ENTITY_EVENT_TYPE_ADDED_NAME))]
        Added,

        /// <summary>
        /// Removed.
        /// </summary>
        [Name("Removed", nameof(Resources.ENTITY_EVENT_TYPE_REMOVED_NAME))]
        Removed,

        /// <summary>
        /// Modified.
        /// </summary>
        [Name("Modified", nameof(Resources.ENTITY_EVENT_TYPE_MODIFIED_NAME))]
        Modified,
    }
}
