using System.ComponentModel.DataAnnotations;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Instance id type.
    /// </summary>
    public enum InstanceIdType
    {
        /// <summary>
        /// Hardware id.
        /// </summary>
        [Name("Hardware Id", nameof(Autogenerated.Resources.INSTANCE_ID_TYPE_HARDWARE_ID_NAME))]
        [ExtendedDescription("Hardware Id", nameof(Autogenerated.Resources.INSTANCE_ID_TYPE_HARDWARE_ID_DESCRIPTION))]
        HardwareId = 0,

        /// <summary>
        /// Instance id.
        /// </summary>
        [Name("Instance Id", nameof(Autogenerated.Resources.INSTANCE_ID_TYPE_HARDWARE_ID_NAME))]
        [ExtendedDescription("Instance Id", nameof(Autogenerated.Resources.INSTANCE_ID_TYPE_INSTANCE_ID_DESCRIPTION))]
        InstanceId = 1,
    }
}
