using System.ComponentModel.DataAnnotations;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Inventory adjustment reasons enumeration.
    /// </summary>
    public enum InventoryAdjustmentReasons
    {
        /// <summary>
        /// Product expired.
        /// </summary>
        [Name("Expired", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.INVENTORY_ADJUSTMENT_REASONS_EXPIRED))]
        Expired = -1,

        /// <summary>
        /// Product packaging is damaged.
        /// </summary>
        [Name("Damaged packaging", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.INVENTORY_ADJUSTMENT_REASONS_DAMAGED))]
        Damaged = -2,
        
        /// <summary>
        /// Product is damaged.
        /// </summary>
        [Name("Damaged item", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.INVENTORY_ADJUSTMENT_REASONS_DAMAGED_ITEM))]
        DamagedItem = -3,
        
        /// <summary>
        /// Product is lost.
        /// </summary>
        [Name("Lost", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.INVENTORY_ADJUSTMENT_REASONS_LOST))]
        Lost = -4,
        
        /// <summary>
        /// Product is not in demand.
        /// </summary>
        [Name("Not in demand", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.INVENTORY_ADJUSTMENT_REASONS_NOT_IN_DEMAND))]
        NotInDemand = -5,
        
        /// <summary>
        /// Force major circumstances.
        /// </summary>
        [Name("Force major", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.INVENTORY_ADJUSTMENT_REASONS_FORCE_MAJOR))]
        ForceMajor = -6,
    }
}
