using System.ComponentModel.DataAnnotations;

namespace Gizmo.Web.Api
{
    /// <summary>
    /// Inventory adjustment type.
    /// </summary>
    public enum InventoryAdjustmentType
    {
        /// <summary>
        /// Write off.
        /// </summary>
        /// <remarks>
        /// Write off is used to remove items from inventory that are no longer sellable or usable, such as lost,expired or damaged items.
        /// </remarks>
        [Name("Write off", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.INVENTORY_ADJUSTMENT_TYPE_WRITE_OFF))]
        WriteOff = 0,

        /// <summary>
        /// Sale by cost.
        /// </summary>
        /// <remarks>
        /// Items are sold at the cost price, which is useful for selling items that are not in demand or have expired.
        /// </remarks>
        [Name("Sale by cost", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.INVENTORY_ADJUSTMENT_TYPE_SALE_BY_COST))]
        SaleByCost = 1,

        /// <summary>
        /// Sale by price.
        /// </summary>
        /// <remarks>
        /// Items are sold at the retail price, which is useful for selling items that are in demand.
        /// </remarks>
        [Name("Sale by price", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.INVENTORY_ADJUSTMENT_TYPE_SALE_BY_PRICE))]
        SaleByPrice = 2,
    }
}
