using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Invoice status.
    /// </summary>
    public enum InvoiceStatus
    {
        /// <summary>
        /// Unpaid.
        /// </summary>
        [Name("Unpaid", nameof(Resources.INVOICE_STATUS_UNPAID_NAME))]
        Unpaid = 0,

        /// <summary>
        /// Partially paid.
        /// </summary>
        [Name("Unpaid", nameof(Resources.INVOICE_STATUS_PARTIALLY_PAID_NAME))]
        PartiallyPaid = 1,

        /// <summary>
        /// Paid.
        /// </summary>
        [Name("Unpaid", nameof(Resources.INVOICE_STATUS_PAID_NAME))]
        Paid = 2,
    }
}
