using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// The state of a user's ladder standing within the current period.
    /// </summary>
    public enum LadderStandingState
    {
        /// <summary>
        /// The current level is not yet re-earned this period. Not a warning — on day one of a
        /// period everyone is earning.
        /// </summary>
        [Name("Earning", nameof(Resources.LADDER_STANDING_STATE_EARNING_NAME))]
        Earning = 0,

        /// <summary>
        /// The current level is re-earned for this period, or held unconditionally.
        /// </summary>
        [Name("Secured", nameof(Resources.LADDER_STANDING_STATE_SECURED_NAME))]
        Secured = 1,

        /// <summary>
        /// A higher level is satisfied but the promotion is pinned to the period end —
        /// promote-on-settle-only, or stepwise promotion.
        /// </summary>
        [Name("Awaiting", nameof(Resources.LADDER_STANDING_STATE_AWAITING_NAME))]
        Awaiting = 2,
    }
}
