using System.ComponentModel.DataAnnotations;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// License state.
    /// </summary>
    public enum LicenseState
    {
        /// <summary>
        /// Valid.
        /// </summary>
        [Name("Valid", nameof(Autogenerated.Resources.LICENSE_STATE_VALID_NAME))]
        [ExtendedDescription("Valid", nameof(Autogenerated.Resources.LICENSE_STATE_VALID_DESCRIPTION))]
        Valid,

        /// <summary>
        /// Disabled instance.
        /// </summary>
        [Name("Disabled instance id", nameof(Autogenerated.Resources.LICENSE_STATE_DISABLED_INSTANCE_ID_NAME))]
        [ExtendedDescription("Instance id is disabled/blocked", nameof(Autogenerated.Resources.LICENSE_STATE_DISABLED_INSTANCE_ID_DESCRIPTION))]
        DisabledInstanceId,

        /// <summary>
        /// Disabled license.
        /// </summary>
        [Name("Disabled", nameof(Autogenerated.Resources.LICENSE_STATE_DISABLED_NAME))]
        [ExtendedDescription("License is disabled", nameof(Autogenerated.Resources.LICENSE_STATE_DISABLED_NAME))]
        Disabled,

        /// <summary>
        /// Expired.
        /// </summary>
        [Name("Expired", nameof(Autogenerated.Resources.LICENSE_STATE_EXPIRED_NAME))]
        [ExtendedDescription("License is expired", nameof(Autogenerated.Resources.LICENSE_STATE_EXPIRED_DESCRIPTION))]
        Expired,

        /// <summary>
        /// Unauthorized.
        /// </summary>
        [Name("Unauthorized", nameof(Autogenerated.Resources.LICENSE_STATE_UNAUTHORIZED_NAME))]
        [ExtendedDescription("Unauthorized", nameof(Autogenerated.Resources.LICENSE_STATE_UNAUTHORIZED_DESCRIPTION))]
        Unauthorized,

        /// <summary>
        /// License is invalid.
        /// </summary>
        [Name("Invalid", nameof(Autogenerated.Resources.LICENSE_STATE_INVALID_NAME))]
        [ExtendedDescription("Local license is invalid", nameof(Autogenerated.Resources.LICENSE_STATE_INVALID_DESCRIPTION))]
        Invalid,
    }
}
