using System.ComponentModel.DataAnnotations;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// License type.
    /// </summary>
    public enum LicenseType
    {
        /// <summary>
        /// Undetermined.
        /// </summary>
        [Name("Undetermined", nameof(Autogenerated.Resources.LICENSE_TYPE_UNDETERMINED_NAME))]
        [ExtendedDescription("License type is undetermined", nameof(Autogenerated.Resources.LICENSE_TYPE_UNDETERMINED_DESCRIPTION))]
        Undetermined,
        /// <summary>
        /// Trial.
        /// </summary>
        [Name("Trial", nameof(Autogenerated.Resources.LICENSE_TYPE_TRIAL_NAME))]
        [ExtendedDescription("Trial license", nameof(Autogenerated.Resources.LICENSE_TYPE_TRIAL_DESCRIPTION))]
        Trial,
        /// <summary>
        /// Normal subscription.
        /// </summary>
        [Name("Normal", nameof(Autogenerated.Resources.LICENSE_TYPE_NORMAL_NAME))]
        [ExtendedDescription("Normal license", nameof(Autogenerated.Resources.LICENSE_TYPE_NORMAL_DESCRIPTION))]
        Normal,
    }
}
