using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// User login result.
    /// </summary>
    [Flags()]
    public enum LoginResult
    {
        /// <summary>
        /// Login was successful.
        /// </summary>
        [Name("Login success", nameof(Resources.LOGIN_RESULT_SUCCESS_NAME))]
        [ExtendedDescription("The user login was successful", nameof(Resources.LOGIN_RESULT_SUCCESS_DESCRIPTION))]
        Success = 0,

        /// <summary>
        /// Invalid parameters specified.
        /// </summary>
        [Name("Invalid parameters", nameof(Resources.LOGIN_RESULT_INVALID_PARAMETERS_NAME))]
        [ExtendedDescription("The specified parameters are invalid", nameof(Resources.LOGIN_RESULT_INVALID_PARAMETERS_DESCRIPTION))]
        InvalidParameters = 1,

        /// <summary>
        /// Account is disabled.
        /// </summary>
        [Name("Account disabled", nameof(Resources.LOGIN_RESULT_ACCOUNT_DISABLED_NAME))]
        [ExtendedDescription("The specified user account is banned", nameof(Resources.LOGIN_RESULT_ACCOUNT_DISABLED_DESCRIPTION))]
        AccountDisabled = 2,

        /// <summary>
        /// Username is invalid.
        /// </summary>
        [Name("Invalid username", nameof(Resources.LOGIN_RESULT_INVALID_USERNAME_NAME))]
        [ExtendedDescription("The specified username is invalid", nameof(Resources.LOGIN_RESULT_INVALID_USERNAME_DESCRIPTION))]
        InvalidUserName = 4,

        /// <summary>
        /// Password is invalid.
        /// </summary>
        [Name("Invalid password", nameof(Resources.LOGIN_RESULT_INVALID_PASSWORD_NAME))]
        [ExtendedDescription("The specified password is invalid", nameof(Resources.LOGIN_RESULT_INVALID_PASSWORD_DESCRIPTION))]
        InvalidPassword = 8,

        /// <summary>
        /// Generic internal error.
        /// </summary>
        [Name("Login failed", nameof(Resources.LOGIN_RESULT_FAILED_NAME))]
        [ExtendedDescription("Unspecified login error", nameof(Resources.LOGIN_RESULT_FAILED_DESCRIPTION))]
        Failed = 16,

        /// <summary>
        /// Login was denied.
        /// </summary>
        [Name("Login denied", nameof(Resources.LOGIN_RESULT_DENIED_NAME))]
        [ExtendedDescription("Login was denied", nameof(Resources.LOGIN_RESULT_DENIED_DESCRIPTION))]
        Denied = 32,

        /// <summary>
        /// Function timed out.
        /// </summary>
        [Obsolete()]
        TimedOut = 64,

        /// <summary>
        /// Login function cannot be executed.
        /// </summary>
        [Obsolete()]
        CantExecute = 128,

        /// <summary>
        /// User already logged in.
        /// </summary>
        [Name("Already logged in", nameof(Resources.LOGIN_RESULT_ALREADY_LOGGED_IN_NAME))]
        [ExtendedDescription("User is already logged in", nameof(Resources.LOGIN_RESULT_ALREADY_LOGGED_IN_DESCRIPTION))]
        AlreadyLoggedIn = 256,

        /// <summary>
        /// Login in progress.
        /// </summary>
        [Obsolete()]
        [Name("In progress", nameof(Resources.LOGIN_RESULT_LOGIN_IN_PROGRESS_NAME))]
        [ExtendedDescription("Login in progress", nameof(Resources.LOGIN_RESULT_LOGIN_IN_PROGRESS_DESCRIPTION))]
        LoginInProgress = 512,

        /// <summary>
        /// Logout in progress.
        /// </summary>
        [Obsolete()]
        [Name("In progress", nameof(Resources.LOGIN_RESULT_LOGOUT_IN_PROGRESS_NAME))]
        [ExtendedDescription("Logout in progress", nameof(Resources.LOGIN_RESULT_LOGOUT_IN_PROGRESS_DESCRIPTION))]
        LogoutInProgress = 1024,

        /// <summary>
        /// Invalid user id.
        /// </summary>
        [Name("Invalid user", nameof(Resources.LOGIN_RESULT_INVALID_USER_ID_NAME))]
        [ExtendedDescription("The specified user id is invalid", nameof(Resources.LOGIN_RESULT_INVALID_USER_ID_DESCRIPTION))]
        InvalidUserId = 2048,

        /// <summary>
        /// Invalid host id.
        /// </summary>
        [Name("Invalid host", nameof(Resources.LOGIN_RESULT_INVALID_HOST_ID_NAME))]
        [ExtendedDescription("The specified host id is invalid", nameof(Resources.LOGIN_RESULT_INVALID_HOST_ID_DESCRIPTION))]
        InvalidHostId = 4096,

        /// <summary>
        /// Maximum sessions reached.
        /// </summary>
        [Name("Maximum sessions reached", nameof(Resources.LOGIN_RESULT_MAXIMUM_SESSIONS_REACHED_NAME))]
        [ExtendedDescription("Login failed due to maximum sessions reached", nameof(Resources.LOGIN_RESULT_MAXIMUM_SESSIONS_REACHED_DESCRIPTION))]
        MaximumSessionsReached = 8192,

        /// <summary>
        /// Insufficient balance.
        /// </summary>
        [Name("Insufficient balance", nameof(Resources.LOGIN_RESULT_INSUFFICIENT_BALANCE_NAME))]
        [ExtendedDescription("The specified user has insufficient balance", nameof(Resources.LOGIN_RESULT_INSUFFICIENT_BALANCE_DESCRIPTION))]
        InsufficientBalance = 16384,

        /// <summary>
        /// Invalid user group was specified for login.
        /// </summary>
        [Name("Invalid user group", nameof(Resources.LOGIN_RESULT_INVALID_USER_GROUP_ID_NAME))]
        [ExtendedDescription("The specified user group id is invalid", nameof(Resources.LOGIN_RESULT_INVALID_USER_GROUP_ID_DESCRIPTION))]
        InvalidUserGroupId = 32768,

        /// <summary>
        /// Slot in use.
        /// </summary>
        [Name("Slot is already in use", nameof(Resources.LOGIN_RESULT_SLOT_IN_USE_NAME))]
        [ExtendedDescription("The specified slot is already in use", nameof(Resources.LOGIN_RESULT_SLOT_IN_USE_DESCRIPTION))]
        SlotInUse = 65536,

        /// <summary>
        /// Slot invalid.
        /// </summary>
        [Name("Invalid slot", nameof(Resources.LOGIN_RESULT_INVALID_SLOT_NAME))]
        [ExtendedDescription("The specified slot is invalid", nameof(Resources.LOGIN_RESULT_INVALID_SLOT_DESCRIPTION))]
        SlotInvalid = 131072,

        /// <summary>
        /// Not in waiting line.
        /// </summary>
        [Name("Not in waiting line", nameof(Resources.LOGIN_RESULT_NOT_IN_WAITING_LINE_NAME))]
        [ExtendedDescription("The specified user is not in waiting line", nameof(Resources.LOGIN_RESULT_NOT_IN_WAITING_LINE_DESCRIPTION))]
        NotInWaitingLine = 262144,

        /// <summary>
        /// Credentials pair is invalid.
        /// </summary>
        [Name("Invalid username or password", nameof(Resources.LOGIN_RESULT_INVALID_CREDENTIALS_NAME))]
        [ExtendedDescription("The specified username or password is invalid", nameof(Resources.LOGIN_RESULT_INVALID_CREDENTIALS_DESCRIPTION))]
        InvalidCredentials = InvalidPassword | InvalidUserName,

        /// <summary>
        /// User group use not allowed for the operator.
        /// </summary>
        [Name("Usergroup login denied for operator", nameof(Resources.LOGIN_RESULT_OPERATOR_USER_GROUP_DENIED_NAME))]
        [ExtendedDescription("Usergroup not allowed to login from manager", nameof(Resources.LOGIN_RESULT_OPERATOR_USER_GROUP_DENIED_DESCRIPTION))]
        OperatorUserGroupDenied = 524288,

        /// <summary>
        /// Login is restricted by age-hour restrictions.
        /// </summary>
        [Name("Login age restrictions", nameof(Resources.LOGIN_RESULT_RESTRICTED_BY_AGE_NAME))]
        [ExtendedDescription("Login is not allowed at this time due to age restrictions configuration", nameof(Resources.LOGIN_RESULT_RESTRICTED_BY_AGE_DESCRIPTION))]
        RestrictedByAge = 1048576,
    }
}
