using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Payment intent state.
    /// </summary>
    public enum PaymentIntentState
    {
        /// <summary>
        /// The intent is pending.
        /// </summary>
        [Name("Pending", nameof(Resources.PAYMENT_INTENT_STATE_PENDING))]
        Pending = 0,

        /// <summary>
        /// The intent is completed.
        /// </summary>
        [Name("Completed", nameof(Resources.PAYMENT_INTENT_STATE_COMPLETED))]
        Completed = 1,

        /// <summary>
        /// The intent is failed.
        /// </summary>
        [Name("Failed", nameof(Resources.PAYMENT_INTENT_STATE_FAILED))]
        Failed = 2,

        /// <summary>
        /// The intent is expired.
        /// </summary>
        [Name("Expired", nameof(Resources.PAYMENT_INTENT_STATE_EXPIRED))]
        Expired = 3,

        /// <summary>
        /// The intent is cancelled.
        /// </summary>
        [Name("Cancelled", nameof(Resources.PAYMENT_INTENT_STATE_CANCELLED))]
        Cancelled = 4,

        /// <summary>
        /// The payment captured.
        /// </summary>
        [Name("Captured", nameof(Resources.PAYMENT_INTENT_STATE_CAPTURED))]
        Captured = 5,

        /// <summary>
        /// Payment declined.
        /// </summary>
        [Name("Declined", nameof(Resources.PAYMENT_INTENT_STATE_DECLINED))]
        Declined = 6,
    }
}
