using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Payment transaction direction.
    /// </summary>
    public enum PaymentTransactionDirection
    {
        /// <summary>
        /// In payment direction.
        /// </summary>
        /// <remarks>
        /// This will indicate payments that we have received.
        /// </remarks>
        [Name("Incoming", nameof(Resources.PAYMENT_TRANSACTION_DIRECTION_IN))]
        In = 0,

        /// <summary>
        /// Out payment direction.
        /// </summary>
        /// <remarks>
        /// This will indicate payments that we have paid out, for example refunds or register transactions.
        /// </remarks>
        [Name("Outgoing", nameof(Resources.PAYMENT_TRANSACTION_DIRECTION_OUT))]
        Out = 1,
    }
}
