using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Product group delete result.
    /// </summary>
    public enum ProductGroupDeleteResult
    {
        /// <summary>
        /// Delete was successful.
        /// </summary>
        [Name("Product group delete success", nameof(Resources.PRODUCT_GROUP_DELETE_RESULT_SUCCESS_NAME))]
        [ExtendedDescription("The product group deletion was successful", nameof(Resources.PRODUCT_GROUP_DELETE_RESULT_SUCCESS_DESCRIPTION))]
        Success = 0,

        /// <summary>
        /// Failed to delete product group.
        /// </summary>
        [Name("Failed to delete product group", nameof(Resources.PRODUCT_GROUP_DELETE_RESULT_FAILED_NAME))]
        [ExtendedDescription("Failed to delete product group", nameof(Resources.PRODUCT_GROUP_DELETE_RESULT_FAILED_DESCRIPTION))]
        Failed = 1,
        /// <summary>
        /// Failed to delete product group.
        /// </summary>
        [Name("Failed to delete product group", nameof(Resources.PRODUCT_GROUP_DELETE_RESULT_NON_EMPTY_NAME))]
        [ExtendedDescription("Failed to delete product group", nameof(Resources.PRODUCT_GROUP_DELETE_RESULT_NON_EMPTY_DESCRIPTION))]
        NonEmpty = 2,

    }
}
