using System.ComponentModel.DataAnnotations;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Promotion limit types.
    /// </summary>
    public enum PromotionLimitType
    {
        /// <summary>
        /// Total limit.
        /// </summary>
        [Name("Total", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.PROMOTION_LIMIT_TYPE_TOTAL))]
        Total = 0,

        /// <summary>
        /// Per user limit.
        /// </summary>
        [Name("PerUser", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.PROMOTION_LIMIT_TYPE_PER_USER))]
        PerUser = 1,

        /// <summary>
        /// Daily limit.
        /// </summary>
        [Name("Daily", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.PROMOTION_LIMIT_TYPE_DAILY))]
        Daily = 2,

        /// <summary>
        /// Weekly limit.
        /// </summary>
        [Name("Weekly", nameof(Gizmo.Web.Api.Models.Autogenerated.Resources.PROMOTION_LIMIT_TYPE_WEEKLY))]
        Weekly = 3,
    }
}
