using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Reservation current confirmed result.
    /// </summary>
    public enum ReservationCurrentConfirmedResult
    {
        /// <summary>
        /// Confirmed.
        /// </summary>
        [Name("Confirmed", nameof(Resources.RESERVATION_CURRENT_CONFIRMED_RESULT_CONFIRMED_NAME))]
        Confirmed = 0,

        /// <summary>
        /// No reservation.
        /// </summary>
        [Name("No reservation", nameof(Resources.RESERVATION_CURRENT_CONFIRMED_RESULT_NO_RESERVATION_NAME))]
        NoReservation = 1,

        /// <summary>
        /// Unconfirmed.
        /// </summary>
        [Name("Unconfirmed", nameof(Resources.RESERVATION_CURRENT_CONFIRMED_RESULT_UNCONFIRMED_NAME))]
        Unconfirmed = 2
    }
}
