using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Reserve guest result.
    /// </summary>
    public enum ReserveGuestResult
    {
        /// <summary>
        /// Success.
        /// </summary>
        [Name("Guest reserved", nameof(Resources.RESERVE_GUEST_RESULT_SUCCESS_NAME))]
        [ExtendedDescription("The guest was reserved successfully", nameof(Resources.RESERVE_GUEST_RESULT_SUCCESS_DESCRIPTION))]
        Success = 0,

        /// <summary>
        /// Invalid slot.
        /// </summary>
        [Name("Invalid slot", nameof(Resources.RESERVE_GUEST_RESULT_INVALID_SLOT_NAME))]
        [ExtendedDescription("The specified slot is invalid for the host, or the user group is not allowed on the host", nameof(Resources.RESERVE_GUEST_RESULT_INVALID_SLOT_DESCRIPTION))]
        InvalidSlot = 1,

        /// <summary>
        /// No guest group to use.
        /// </summary>
        [Name("No guest user group", nameof(Resources.RESERVE_GUEST_RESULT_NO_GUEST_GROUP_NAME))]
        [ExtendedDescription("No user group that allows guest use could be found", nameof(Resources.RESERVE_GUEST_RESULT_NO_GUEST_GROUP_DESCRIPTION))]
        NoGuestGroup = 2,

        /// <summary>
        /// Guest use not allowed.
        /// </summary>
        [Name("Guest use not allowed", nameof(Resources.RESERVE_GUEST_RESULT_GUEST_USE_NOT_ALLOWED_NAME))]
        [ExtendedDescription("The specified user group does not allow guest use", nameof(Resources.RESERVE_GUEST_RESULT_GUEST_USE_NOT_ALLOWED_DESCRIPTION))]
        GuestUseNotAllowed = 3,

        /// <summary>
        /// Host is out of order.
        /// </summary>
        [Name("Host out of order", nameof(Resources.RESERVE_GUEST_RESULT_HOST_OUT_OF_ORDER_NAME))]
        [ExtendedDescription("A guest cannot be reserved on a host that is out of order", nameof(Resources.RESERVE_GUEST_RESULT_HOST_OUT_OF_ORDER_DESCRIPTION))]
        HostOutOfOrder = 4,

        /// <summary>
        /// Max reservations reached.
        /// </summary>
        [Name("Maximum reservations reached", nameof(Resources.RESERVE_GUEST_RESULT_MAX_RESERVATIONS_REACHED_NAME))]
        [ExtendedDescription("The host has no free slot left for a guest reservation", nameof(Resources.RESERVE_GUEST_RESULT_MAX_RESERVATIONS_REACHED_DESCRIPTION))]
        MaxReservationsReached = 5,

        /// <summary>
        /// Slot is in use.
        /// </summary>
        [Name("Slot is already in use", nameof(Resources.RESERVE_GUEST_RESULT_SLOT_IN_USE_NAME))]
        [ExtendedDescription("The specified slot is already reserved by another guest", nameof(Resources.RESERVE_GUEST_RESULT_SLOT_IN_USE_DESCRIPTION))]
        SlotInUse = 6,
    }
}
