using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Reservation confirmation result.
    /// </summary>
    public enum ReservationCurrentConfirmResult
    {
        /// <summary>
        /// Success.
        /// </summary>
        [Name("Success", nameof(Resources.RESERVATION_CURRENT_CONFIRM_RESULT_SUCCESS_NAME))]
        Success = 0,

        /// <summary>
        /// Internal error.
        /// </summary>
        [Name("No reservation", nameof(Resources.RESERVATION_CURRENT_CONFIRM_RESULT_NO_RESERVATION_NAME))]
        NoReservation = 1,

        /// <summary>
        /// Invalid pin.
        /// </summary>
        [Name("Invalid pin", nameof(Resources.RESERVATION_CURRENT_CONFIRM_RESULT_INVALID_PIN_NAME))]
        InvalidPin = 2,

        /// <summary>
        /// Internal error.
        /// </summary>
        [Name("Error", nameof(Resources.RESERVATION_CURRENT_CONFIRM_RESULT_ERROR_NAME))]
        Error = 3,
    }
}
