using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Restriction type.
    /// </summary>
    public enum RestrictionType
    {
        /// <summary>
        /// Unset.
        /// </summary>
        [Name("Unset", nameof(Resources.RESTRICTION_TYPE_UNSET))]
        Unset = 0,

        /// <summary>
        /// File name.
        /// </summary>
        [Name("File Name", nameof(Resources.RESTRICTION_TYPE_FILE_NAME))]
        FileName = 1,

        /// <summary>
        /// Window class name.
        /// </summary>
        [Name("Class Name", nameof(Resources.RESTRICTION_TYPE_CLASS_NAME))]
        ClassName = 2,

        /// <summary>
        /// Window name.
        /// </summary>
        [Name("Window Name", nameof(Resources.RESTRICTION_TYPE_WINDOW_NAME))]
        WindowName = 3,

        /// <summary>
        /// Tray icon.
        /// </summary>
        [Name("Tray Icon", nameof(Resources.RESTRICTION_TYPE_TRAY_ICON))]
        TrayIcon = 4
    }
}
