using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Query filter kinds an achievement signal supports.
    /// Value-identical copy of the extensibility domain enum.
    /// </summary>
    /// <remarks>
    /// Declared per signal (<see cref="AchievementSignalModel.SupportedFilters"/>) and
    /// gates which <see cref="AchievementFiltersModel"/> collections an achievement of
    /// that signal may populate.
    /// </remarks>
    [Flags]
    public enum SignalFilterKinds : long
    {
        /// <summary>
        /// No filters supported.
        /// </summary>
        [Name("None", nameof(Resources.SIGNAL_FILTER_KIND_NONE_NAME))]
        None = 0,

        /// <summary>
        /// Restrict measurement to activity on any of the specified hosts.
        /// </summary>
        [Name("Host", nameof(Resources.SIGNAL_FILTER_KIND_HOST_NAME))]
        Host = 1,

        /// <summary>
        /// Restrict measurement to activity on hosts of any of the specified host groups.
        /// </summary>
        [Name("Host group", nameof(Resources.SIGNAL_FILTER_KIND_HOST_GROUP_NAME))]
        HostGroup = 2,

        // 4 is reserved — was DayTime, merged into DayOfWeek when day-anchored
        // time windows moved onto the day of week filter entries.

        /// <summary>
        /// Restrict measurement to activity settled with any of the specified payment methods.
        /// </summary>
        [Name("Payment method", nameof(Resources.SIGNAL_FILTER_KIND_PAYMENT_METHOD_NAME))]
        PaymentMethod = 8,

        /// <summary>
        /// Provider-interpreted custom key/value parameters (typically plugin signals).
        /// </summary>
        [Name("Parameters", nameof(Resources.SIGNAL_FILTER_KIND_PARAMETERS_NAME))]
        Parameters = 16,

        /// <summary>
        /// Restrict measurement to activity attributed to any of the specified branches.
        /// </summary>
        [Name("Branch", nameof(Resources.SIGNAL_FILTER_KIND_BRANCH_NAME))]
        Branch = 32,

        /// <summary>
        /// Restrict measurement to activity of any of the specified applications.
        /// </summary>
        [Name("App", nameof(Resources.SIGNAL_FILTER_KIND_APP_NAME))]
        App = 64,

        /// <summary>
        /// Restrict measurement to activity of applications in any of the specified app groups.
        /// </summary>
        [Name("App group", nameof(Resources.SIGNAL_FILTER_KIND_APP_GROUP_NAME))]
        AppGroup = 128,

        /// <summary>
        /// Restrict measurement to activity involving any of the specified products.
        /// </summary>
        [Name("Product", nameof(Resources.SIGNAL_FILTER_KIND_PRODUCT_NAME))]
        Product = 256,

        /// <summary>
        /// Restrict measurement to activity involving products of any of the specified product groups.
        /// </summary>
        [Name("Product group", nameof(Resources.SIGNAL_FILTER_KIND_PRODUCT_GROUP_NAME))]
        ProductGroup = 512,

        /// <summary>
        /// Restrict measurement to activity billed under any of the specified bill profiles.
        /// </summary>
        [Name("Bill profile", nameof(Resources.SIGNAL_FILTER_KIND_BILL_PROFILE_NAME))]
        BillProfile = 1024,

        /// <summary>
        /// Restrict measurement to day-anchored, optionally time-narrowed windows.
        /// </summary>
        [Name("Day of week", nameof(Resources.SIGNAL_FILTER_KIND_DAY_OF_WEEK_NAME))]
        DayOfWeek = 2048,

        /// <summary>
        /// Restrict measurement to activity of any of the specified application executables.
        /// </summary>
        [Name("App executable", nameof(Resources.SIGNAL_FILTER_KIND_APP_EXE_NAME))]
        AppExe = 4096,

        /// <summary>
        /// Restrict measurement to activity of applications in any of the specified app categories.
        /// </summary>
        [Name("App category", nameof(Resources.SIGNAL_FILTER_KIND_APP_CATEGORY_NAME))]
        AppCategory = 8192,
    }
}
