using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Native measurement unit of an achievement signal.
    /// Value-identical copy of the extensibility domain enum.
    /// </summary>
    /// <remarks>
    /// Determines how raw signal values are displayed and formatted. Providers always
    /// return values in their native unit; any conversion is a configuration concern.
    /// </remarks>
    public enum SignalUnit
    {
        /// <summary>
        /// Plain occurrence count (e.g. visits, matches played).
        /// </summary>
        [Name("Count", nameof(Resources.SIGNAL_UNIT_COUNT_NAME))]
        Count = 0,

        /// <summary>
        /// Monetary amount in operator currency (e.g. money spent).
        /// </summary>
        [Name("Currency", nameof(Resources.SIGNAL_UNIT_CURRENCY_NAME))]
        Currency = 1,

        /// <summary>
        /// Time duration expressed in seconds (e.g. play time).
        /// </summary>
        [Name("Duration", nameof(Resources.SIGNAL_UNIT_DURATION_NAME))]
        Duration = 2,

        /// <summary>
        /// Loyalty points (e.g. points earned).
        /// </summary>
        [Name("Points", nameof(Resources.SIGNAL_UNIT_POINTS_NAME))]
        Points = 3,

        /// <summary>
        /// Time duration expressed in whole days (e.g. days since registration).
        /// </summary>
        [Name("Days", nameof(Resources.SIGNAL_UNIT_DAYS_NAME))]
        Days = 4,
    }
}
