using System.ComponentModel.DataAnnotations;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Stock level type enumeration.
    /// </summary>
    public enum StockLevelType
    {
        /// <summary>
        /// Any stock level type.
        /// </summary>
        [Name("Any", nameof(Autogenerated.Resources.STOCK_LEVEL_TYPE_ANY))]
        Any = 0,

        /// <summary>
        /// Low stock level.
        /// </summary>
        /// <remarks>
        /// This is used to indicate that the stock level is below a certain threshold, which is typically defined by alert level.
        /// </remarks>
        [Name("Low", nameof(Autogenerated.Resources.STOCK_LEVEL_TYPE_LOW))]
        Low = 1,

        /// <summary>
        /// Product is out of stock.
        /// </summary>
        [Name("Out of stock", nameof(Autogenerated.Resources.STOCK_LEVEL_TYPE_OUT_OF_STOCK))]
        OutOfStock = 2,
    }
}
