using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Stock type.
    /// </summary>
    public enum StockType
    {
        /// <summary>
        /// Selling point.
        /// </summary>
        [Name("Selling Point", nameof(Resources.STOCK_TYPE_SELLING_POINT))]
        SellingPoint = 0,

        /// <summary>
        /// Warehouse.
        /// </summary>
        [Name("Warehouse", nameof(Resources.STOCK_TYPE_WAREHOUSE))]
        Warehouse = 1
    }
}
