using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Stock count type.
    /// </summary>
    public enum StockCountType
    {
        [Name("Manual", nameof(Resources.SHIFT_COUNT_TYPE_DEFAULT))]
        Default = 0,

        [Name("Shift Open", nameof(Resources.SHIFT_COUNT_TYPE_SHIFT_OPEN))]
        ShiftOpen = 1,

        [Name("Shift Close", nameof(Resources.SHIFT_COUNT_TYPE_SHIFT_CLOSE))]
        ShiftClose = 2,
    }
}
