using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Stock transaction type.
    /// </summary>
    public enum StockTransactionType
    {
        /// <summary>
        /// Add.
        /// </summary>
        [Name("Add", nameof(Resources.STOCK_TRANSACTION_TYPE_ADD_NAME))]
        Add = 0,

        /// <summary>
        /// Remove.
        /// </summary>
        [Name("Remove", nameof(Resources.STOCK_TRANSACTION_TYPE_REMOVE_NAME))]
        Remove = 1,

        /// <summary>
        /// Sale.
        /// </summary>
        [Name("Sale", nameof(Resources.STOCK_TRANSACTION_TYPE_SALE_NAME))]
        Sale = 2,

        /// <summary>
        /// Set.
        /// </summary>
        [Name("Set", nameof(Resources.STOCK_TRANSACTION_TYPE_SET_NAME))]
        Set = 3,

        /// <summary>
        /// Return.
        /// </summary>
        [Name("Return", nameof(Resources.STOCK_TRANSACTION_TYPE_RETURN_NAME))]
        Return = 4,
    }
}
