using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Discount target group requirement.
    /// </summary>
    public enum TargetGroupRequirement
    {
        /// <summary>
        /// All.
        /// </summary>
        [Name("All", nameof(Resources.TARGET_GROUP_REQUIREMENT_ALL))]
        All = 0,

        /// <summary>
        /// Any.
        /// </summary>
        [Name("Any", nameof(Resources.TARGET_GROUP_REQUIREMENT_ANY))]
        Any = 1,
    }
}
