using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Task types.
    /// </summary>
    public enum TaskType
    {
        /// <summary>
        /// Process.
        /// </summary>
        [Name("Process", nameof(Resources.TASK_TYPE_PROCESS_NAME))]
        Process = 0,

        /// <summary>
        /// Script.
        /// </summary>
        [Name("Script", nameof(Resources.TASK_TYPE_SCRIPT_NAME))]
        Script = 1,

        /// <summary>
        /// Notification.
        /// </summary>
        [Name("Notification", nameof(Resources.TASK_TYPE_NOTIFICATION_NAME))]
        Notification = 4,

        /// <summary>
        /// Junction.
        /// </summary>
        [Name("Junction", nameof(Resources.TASK_TYPE_JUNCTION_NAME))]
        Junction = 5
    }
}
