using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Defines time usage type.
    /// </summary>
    public enum UsageType
    {
        /// <summary>
        /// None.
        /// </summary>
        [Name("Time", nameof(Resources.USAGE_TYPE_NONE_NAME))]
        None = 0,

        /// <summary>
        /// Billing profile rate.
        /// </summary>
        [Name("Rate", nameof(Resources.USAGE_TYPE_RATE_NAME))]
        Rate = 1,

        /// <summary>
        /// Fixed time.
        /// </summary>
        [Name("Fixed time", nameof(Resources.USAGE_TYPE_TIME_FIXED_NAME))]
        TimeFixed = 2,

        /// <summary>
        /// Time offer.
        /// </summary>
        [Name("Time offer", nameof(Resources.USAGE_TYPE_TIME_OFFER_NAME))]
        TimeOffer = 3,
    }
}
