using System;
using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// User session states.
    /// </summary>
    [Flags()]
    public enum UserSessionState
    {
        /// <summary>
        /// Session initialized.
        /// </summary>
        [Name("Waiting", nameof(Resources.USER_SESSION_STATE_NONE_NAME))]
        None = 0,
        /// <summary>
        /// Session is active.
        /// </summary>

        [Name("Active", nameof(Resources.USER_SESSION_STATE_ACTIVE_NAME))]
        Active = 1,
        /// <summary>
        /// Session ended.
        /// </summary>

        [Name("Ended", nameof(Resources.USER_SESSION_STATE_ENDED_NAME))]
        Ended = 2,

        /// <summary>
        /// Session pending termination.
        /// </summary>
        [Name("Pending", nameof(Resources.USER_SESSION_STATE_PENDING_NAME))]
        Pending = 4 | Active,

        /// <summary>
        /// Session paused and pending activation.
        /// </summary>        
        [Name("Paused", nameof(Resources.USER_SESSION_STATE_PAUSED_NAME))]
        Paused = 8 | Active,

        /// <summary>
        /// Session is moving.
        /// </summary>
        [Name("Waiting", nameof(Resources.USER_SESSION_STATE_MOVED_NAME))]
        Moved = 16 | Active,

        /// <summary>
        /// Grace period.
        /// </summary>
        [Name("Grace", nameof(Resources.USER_SESSION_STATE_GRACE_NAME))]
        Grace = 32 | Active
    }
}
