using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// The state of one earned reward as a person reads it — computed on the server so every
    /// surface renders the same chip for the same facts.
    /// </summary>
    /// <remarks>
    /// Derived from the stored <see cref="AchievementChallengeRewardStatus"/> and the processing
    /// operator. The stored status separates the two ways a reward can be undelivered (an
    /// automatic grant that has not run yet versus one waiting at the counter) — an operational
    /// distinction that both read as pending; what a reader cares about instead is who delivered
    /// a terminal row, the system or an operator, which the status alone cannot say.
    /// </remarks>
    public enum UserAchievementRewardState
    {
        /// <summary>
        /// Earned but not delivered — either awaiting its automatic grant or waiting for an
        /// operator to hand it over.
        /// </summary>
        [Name("Pending", nameof(Resources.USER_ACHIEVEMENT_REWARD_STATE_PENDING_NAME))]
        Pending = 0,

        /// <summary>
        /// Delivered automatically by the system.
        /// </summary>
        [Name("Delivered", nameof(Resources.USER_ACHIEVEMENT_REWARD_STATE_DELIVERED_NAME))]
        Delivered = 1,

        /// <summary>
        /// Handed over by an operator.
        /// </summary>
        [Name("Claimed", nameof(Resources.USER_ACHIEVEMENT_REWARD_STATE_CLAIMED_NAME))]
        Claimed = 2,

        /// <summary>
        /// Declined — terminal, nothing was delivered; an operator may re-offer it.
        /// </summary>
        [Name("Declined", nameof(Resources.USER_ACHIEVEMENT_REWARD_STATE_DECLINED_NAME))]
        Declined = 3,
    }
}
