using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// The state of one challenge for one user — computed on the server so every surface
    /// renders the same card for the same facts.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Members are declared in ascending precedence: when several apply, the highest value
    /// wins. <see cref="Active"/> is the default so an unset value never reads as a terminal
    /// state.
    /// </para>
    /// <para>
    /// Three of them — <see cref="Unmeasurable"/>, <see cref="Blocked"/> and
    /// <see cref="Unreachable"/> — depend on how far the user has come, so they are only
    /// evaluated when the request collects progress. Without it a challenge reports the state
    /// its configuration alone establishes.
    /// </para>
    /// </remarks>
    public enum UserAchievementChallengeState
    {
        /// <summary>
        /// Open and earnable — the user can still complete it.
        /// </summary>
        [Name("Active", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_ACTIVE_NAME))]
        Active = 0,

        /// <summary>
        /// The window has not opened yet. Reserved: the challenges view lists started
        /// challenges only, so it is never returned today.
        /// </summary>
        [Name("Not started", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_NOT_STARTED_NAME))]
        NotStarted = 1,

        /// <summary>
        /// An unmet requirement measures a signal that has no registered provider, so it
        /// cannot advance until the provider returns.
        /// </summary>
        [Name("Unmeasurable", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_UNMEASURABLE_NAME))]
        Unmeasurable = 2,

        /// <summary>
        /// An unmet requirement is paused or archived. Challenge requirements never drop out
        /// — they are judged on already-recorded completions — so the challenge waits for the
        /// achievement to come back.
        /// </summary>
        [Name("Blocked", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_BLOCKED_NAME))]
        Blocked = 3,

        /// <summary>
        /// The challenge itself is paused; earned completions stand, no new ones materialize.
        /// </summary>
        [Name("Paused", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_PAUSED_NAME))]
        Paused = 4,

        /// <summary>
        /// Too little of the window remains for the user to finish: what an unmet requirement
        /// still needs exceeds the completions its range can still yield before the window
        /// closes.
        /// </summary>
        [Name("Unreachable", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_UNREACHABLE_NAME))]
        Unreachable = 5,

        /// <summary>
        /// The account cannot be granted rewards — a guest, deleted or banned user. Progress
        /// is not measured for them.
        /// </summary>
        [Name("Ineligible", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_INELIGIBLE_NAME))]
        Ineligible = 6,

        /// <summary>
        /// The shared completion pool is used up — nobody can earn this challenge again.
        /// </summary>
        [Name("Pool exhausted", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_POOL_EXHAUSTED_NAME))]
        PoolExhausted = 7,

        /// <summary>
        /// The window has closed. Activity that happened before the close can still be
        /// evaluated into a completion for a short grace period afterwards.
        /// </summary>
        [Name("Ended", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_ENDED_NAME))]
        Ended = 8,

        /// <summary>
        /// Archived from the catalog — listed only because the user has completions on it.
        /// </summary>
        [Name("Archived", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_ARCHIVED_NAME))]
        Archived = 9,

        /// <summary>
        /// The user earned every completion the challenge offers them.
        /// </summary>
        [Name("Done", nameof(Resources.USER_ACHIEVEMENT_CHALLENGE_STATE_DONE_NAME))]
        Done = 10,
    }
}
