using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// The state of one achievement in a user's achievements view — computed on the server so
    /// every surface renders the same card for the same facts.
    /// </summary>
    public enum UserAchievementState
    {
        /// <summary>
        /// Earnable right now — the current range instance is below its completion cap.
        /// </summary>
        [Name("Active", nameof(Resources.USER_ACHIEVEMENT_STATE_ACTIVE_NAME))]
        Active = 0,

        /// <summary>
        /// The current range instance is at its completion cap; earning resumes with the next
        /// instance.
        /// </summary>
        [Name("Earned", nameof(Resources.USER_ACHIEVEMENT_STATE_EARNED_NAME))]
        Earned = 1,

        /// <summary>
        /// Paused by the operator — no new completions until re-enabled; visible only because
        /// the user has completions on it.
        /// </summary>
        [Name("Paused", nameof(Resources.USER_ACHIEVEMENT_STATE_PAUSED_NAME))]
        Paused = 2,

        /// <summary>
        /// Archived by the operator — visible only because the user has completions on it.
        /// </summary>
        [Name("Archived", nameof(Resources.USER_ACHIEVEMENT_STATE_ARCHIVED_NAME))]
        Archived = 3,

        /// <summary>
        /// The achievement's signal has no registered provider, so nothing can be measured or
        /// completed until the provider returns.
        /// </summary>
        [Name("Unmeasurable", nameof(Resources.USER_ACHIEVEMENT_STATE_UNMEASURABLE_NAME))]
        Unmeasurable = 4,
    }
}
