using System.ComponentModel.DataAnnotations;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Waiting line states.
    /// </summary>
    public enum WaitingLineState
    {
        /// <summary>
        /// Active.
        /// </summary>
        [Name("Active", nameof(Resources.WAITING_LINE_STATE_ACTIVE_NAME))]
        Active = 0,
        /// <summary>
        /// Processed.
        /// </summary>
       
        [Name("Processed", nameof(Resources.WAITING_LINE_STATE_PROCESSED_NAME))]
        Processed = 2,
       
        /// <summary>
        /// Cancel.
        /// </summary>
        [Name("Cancelled", nameof(Resources.WAITING_LINE_STATE_CANCELED_NAME))]
        Canceled = 1,
    }
}
