using System;

using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Action center entry cancellation event, for an entry whose reason stopped applying.
    /// </summary>
    /// <remarks>
    /// Distinct from resolved and from expired, because it is neither. Nobody dealt with the subject,
    /// so it was not resolved, and its time did not run out, so it did not expire: what it was raised
    /// about simply stopped being true. A customer who left owing money and then logged back in is the
    /// case it exists for. The debt is still owed; it is just no longer something to chase, because
    /// they are standing at a desk.
    /// <para>
    /// Kept apart from the resolved message so a manager can tell "that was paid" from "that customer
    /// came back", which are different things to tell an operator. Nobody acted, so there is no
    /// operator to carry, and no sequence for the same reason the other closing messages have none.
    /// </para>
    /// </remarks>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Entry cancelled", nameof(Resources.ACTION_CENTER_ENTRY_CANCELLED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates an action center entry was cancelled because its reason no longer applies", nameof(Resources.ACTION_CENTER_ENTRY_CANCELLED_EVENT_DESCRIPTION))]
    public sealed class ActionCenterEntryCancelledEventMessage : ActionCenterEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ActionCenterEntryCancelledEventMessage() : base()
        { }

        /// <summary>
        /// Gets the entry that was cancelled.
        /// </summary>
        [Key(1)]
        public required Guid EntryId { get; init; }
    }
}
