using System;

using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Action center entry resolution event, for an entry closed by what it was waiting for.
    /// </summary>
    /// <remarks>
    /// The domain moved on: the order was accepted, the request was answered. It goes to everyone the
    /// entry was addressed to, since a task finished once is finished for all of them, and so it has to
    /// name who did it: unlike a view change, its audience does not already say.
    /// <para>
    /// What each manager does with that is its own decision, since one message reaches the whole
    /// group and the server cannot tailor it per recipient. The intended handling is to remove the
    /// entry at once when the operator is the reader themselves, since they know what they just did,
    /// and otherwise to show briefly who resolved it before removing it, so a task a colleague
    /// handled does not simply vanish.
    /// </para>
    /// <para>
    /// It deliberately does not say how the subject ended. That is the subject's own new state, which
    /// the manager already holds through its lookups for orders and requests, and any single list of
    /// outcomes would have to grow a private vocabulary for every kind: accepted and rejected mean
    /// something for an order, while a host coming back or a debt being paid need words of their own.
    /// The action center only needs to take its pointer away.
    /// </para>
    /// <para>
    /// It carries no sequence. A sequence exists to stop the sync snapshot and the live stream from
    /// announcing the same entry twice, and closing cannot do that: removing an entry is idempotent,
    /// removing one the manager does not hold does nothing, and ids never repeat, so a late close can
    /// never reach a newer entry.
    /// </para>
    /// </remarks>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Entry resolved", nameof(Resources.ACTION_CENTER_ENTRY_RESOLVED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates an action center entry was resolved", nameof(Resources.ACTION_CENTER_ENTRY_RESOLVED_EVENT_DESCRIPTION))]
    public sealed class ActionCenterEntryResolvedEventMessage : ActionCenterEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ActionCenterEntryResolvedEventMessage() : base()
        { }

        /// <summary>
        /// Gets the entry that closed.
        /// </summary>
        [Key(1)]
        public required Guid EntryId { get; init; }

        /// <summary>
        /// Gets the operator whose work in the domain closed it; null when no operator did.
        /// </summary>
        /// <remarks>
        /// Taken from the domain record of who made the change, not from anything done in the action
        /// center, since operators only ever dismiss there. Null is a real answer rather than a missing
        /// one: the system closed it, or the customer did, such as by cancelling their own order.
        /// </remarks>
        [Key(2)]
        public int? OperatorId { get; init; }
    }
}
