using Gizmo.Web.Api.Models;
using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Action center entry creation event.
    /// </summary>
    /// <remarks>
    /// Carries the whole entry, so a manager handles a created entry and a synced one the same way.
    /// The entry names its subject by id and the manager renders it from its own lookups, which is
    /// what keeps it current as the subject changes. This is the only message that carries a
    /// sequence, on the entry, because it is the only one that can announce something the sync
    /// snapshot already contains.
    /// </remarks>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Entry created", nameof(Resources.ACTION_CENTER_ENTRY_CREATED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates an action center entry was created", nameof(Resources.ACTION_CENTER_ENTRY_CREATED_EVENT_DESCRIPTION))]
    public sealed class ActionCenterEntryCreatedEventMessage : ActionCenterEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ActionCenterEntryCreatedEventMessage() : base()
        { }

        /// <summary>
        /// Gets the created entry.
        /// </summary>
        [Key(1)]
        public required ActionCenterEntryModel Entry { get; init; }
    }
}
