using System;

using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Action center entry expiry event, for an informational entry whose time ran out.
    /// </summary>
    /// <remarks>
    /// The server decides when, by its sweep, so every manager drops the entry at the same moment
    /// rather than each by its own clock. Nothing happened to the subject and nobody acted, so there is
    /// nothing to carry beyond which entry it was, and no sequence for the same reason the resolved
    /// message has none.
    /// </remarks>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Entry expired", nameof(Resources.ACTION_CENTER_ENTRY_EXPIRED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates an informational action center entry expired", nameof(Resources.ACTION_CENTER_ENTRY_EXPIRED_EVENT_DESCRIPTION))]
    public sealed class ActionCenterEntryExpiredEventMessage : ActionCenterEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ActionCenterEntryExpiredEventMessage() : base()
        { }

        /// <summary>
        /// Gets the entry that expired.
        /// </summary>
        [Key(1)]
        public required Guid EntryId { get; init; }
    }
}
