using System;

using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Action center entry view state change event.
    /// </summary>
    /// <remarks>
    /// View state belongs to one operator, so this goes to that operator's group alone and lets
    /// their other windows and devices agree. It never changes the entry for anybody else, and it
    /// carries no sequence because view state does not move the entry's.
    /// <para>
    /// It does not name the operator. Every connection that receives it belongs to the operator it
    /// would name, so the field could only ever tell the reader their own id. The server knows the
    /// operator, and uses it to choose the group; it just does not repeat it on the wire.
    /// </para>
    /// <para>
    /// The two flags state the resulting view, not the change that produced it, because a dismiss can
    /// be undone: applying the latest state is right whatever a window missed.
    /// </para>
    /// </remarks>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Entry view changed", nameof(Resources.ACTION_CENTER_ENTRY_VIEW_CHANGED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates an operator read or dismissed an action center entry", nameof(Resources.ACTION_CENTER_ENTRY_VIEW_CHANGED_EVENT_DESCRIPTION))]
    public sealed class ActionCenterEntryViewChangedEventMessage : ActionCenterEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public ActionCenterEntryViewChangedEventMessage() : base()
        { }

        /// <summary>
        /// Gets the entry whose view state changed.
        /// </summary>
        [Key(1)]
        public required Guid EntryId { get; init; }

        /// <summary>
        /// Gets whether the reader has seen the entry.
        /// </summary>
        [Key(2)]
        public bool IsRead { get; init; }

        /// <summary>
        /// Gets whether the reader hid the entry.
        /// </summary>
        [Key(3)]
        public bool IsDismissed { get; init; }
    }
}
