//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Web.Api.Models.Autogenerated {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Web.Api.Models.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates assistance request status change.
        /// </summary>
        public static string ASSISTANCE_REQUEST_CHANGE_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_CHANGE_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ASSISTANCE_REQUEST_CHANGE_EVENT_EVENT_NAME {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_CHANGE_EVENT_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates assistance request creation.
        /// </summary>
        public static string ASSISTANCE_REQUEST_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ASSISTANCE_REQUEST_CREATED_EVENT_EVENT_NAME {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_CREATED_EVENT_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance request related events.
        /// </summary>
        public static string ASSISTANCE_REQUEST_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance request.
        /// </summary>
        public static string ASSISTANCE_REQUEST_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed due to an error.
        /// </summary>
        public static string AUTHENTICATION_STATE_ERROR_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_ERROR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string AUTHENTICATION_STATE_ERROR_NAME {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_ERROR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication state is invalid.
        /// </summary>
        public static string AUTHENTICATION_STATE_INVALID_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_INVALID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string AUTHENTICATION_STATE_INVALID_NAME {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed due to an network error.
        /// </summary>
        public static string AUTHENTICATION_STATE_NETWORK_ERROR_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_NETWORK_ERROR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error.
        /// </summary>
        public static string AUTHENTICATION_STATE_NETWORK_ERROR_NAME {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_NETWORK_ERROR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token present for authentication.
        /// </summary>
        public static string AUTHENTICATION_STATE_NO_TOKEN_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_NO_TOKEN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token.
        /// </summary>
        public static string AUTHENTICATION_STATE_NO_TOKEN_NAME {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_NO_TOKEN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string AUTHENTICATION_STATE_UNAUTHORIZED_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_UNAUTHORIZED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string AUTHENTICATION_STATE_UNAUTHORIZED_NAME {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_UNAUTHORIZED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication valid.
        /// </summary>
        public static string AUTHENTICATION_STATE_VALID_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_VALID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string AUTHENTICATION_STATE_VALID_NAME {
            get {
                return ResourceManager.GetString("AUTHENTICATION_STATE_VALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed due to an error.
        /// </summary>
        public static string AUTHORIZATION_RESULT_ERROR_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_ERROR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string AUTHORIZATION_RESULT_ERROR_NAME {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_ERROR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed due to an invalid instance id.
        /// </summary>
        public static string AUTHORIZATION_RESULT_INVALID_ID_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_INVALID_ID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id.
        /// </summary>
        public static string AUTHORIZATION_RESULT_INVALID_ID_NAME {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_INVALID_ID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed due to an network error.
        /// </summary>
        public static string AUTHORIZATION_RESULT_NETWORK_ERROR_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_NETWORK_ERROR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error.
        /// </summary>
        public static string AUTHORIZATION_RESULT_NETWORK_ERROR_NAME {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_NETWORK_ERROR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization successful.
        /// </summary>
        public static string AUTHORIZATION_RESULT_SUCCESS_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_SUCCESS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string AUTHORIZATION_RESULT_SUCCESS_NAME {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_SUCCESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed due to a expired token.
        /// </summary>
        public static string AUTHORIZATION_RESULT_TOKEN_EXPIRED_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_TOKEN_EXPIRED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expired.
        /// </summary>
        public static string AUTHORIZATION_RESULT_TOKEN_EXPIRED_NAME {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_TOKEN_EXPIRED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string AUTHORIZATION_RESULT_UNAUTHORIZED_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_UNAUTHORIZED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string AUTHORIZATION_RESULT_UNAUTHORIZED_NAME {
            get {
                return ResourceManager.GetString("AUTHORIZATION_RESULT_UNAUTHORIZED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future payments may fail due to card expiration.
        /// </summary>
        public static string AUTHORIZATION_WARNINGS_FUTURE_PAYMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHORIZATION_WARNINGS_FUTURE_PAYMENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future payment warning.
        /// </summary>
        public static string AUTHORIZATION_WARNINGS_FUTURE_PAYMENT_NAME {
            get {
                return ResourceManager.GetString("AUTHORIZATION_WARNINGS_FUTURE_PAYMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string AUTHORIZATION_WARNINGS_NONE_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHORIZATION_WARNINGS_NONE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string AUTHORIZATION_WARNINGS_NONE_NAME {
            get {
                return ResourceManager.GetString("AUTHORIZATION_WARNINGS_NONE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment attempt did not succeed.
        /// </summary>
        public static string AUTHORIZATION_WARNINGS_PAYMENT_FAILURE_DESCRIPTION {
            get {
                return ResourceManager.GetString("AUTHORIZATION_WARNINGS_PAYMENT_FAILURE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failure.
        /// </summary>
        public static string AUTHORIZATION_WARNINGS_PAYMENT_FAILURE_NAME {
            get {
                return ResourceManager.GetString("AUTHORIZATION_WARNINGS_PAYMENT_FAILURE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch created event.
        /// </summary>
        public static string BRANCH_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch created.
        /// </summary>
        public static string BRANCH_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch deleted event.
        /// </summary>
        public static string BRANCH_DELETED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_DELETED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string BRANCH_DELETED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_DELETED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch releated events.
        /// </summary>
        public static string BRANCH_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string BRANCH_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("BRANCH_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator added event.
        /// </summary>
        public static string BRANCH_OPERATOR_ADDED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_ADDED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator added.
        /// </summary>
        public static string BRANCH_OPERATOR_ADDED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_ADDED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators default branch change event.
        /// </summary>
        public static string BRANCH_OPERATOR_DEFAULT_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_DEFAULT_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators default branch change.
        /// </summary>
        public static string BRANCH_OPERATOR_DEFAULT_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_DEFAULT_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator removed event.
        /// </summary>
        public static string BRANCH_OPERATOR_REMOVED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_REMOVED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator removed.
        /// </summary>
        public static string BRANCH_OPERATOR_REMOVED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_REMOVED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch undeleted event.
        /// </summary>
        public static string BRANCH_UNDELETED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_UNDELETED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeleted.
        /// </summary>
        public static string BRANCH_UNDELETED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_UNDELETED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch updated event.
        /// </summary>
        public static string BRANCH_UPDATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_UPDATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch updated.
        /// </summary>
        public static string BRANCH_UPDATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_UPDATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode scanned event.
        /// </summary>
        public static string DEVICE_BARCODE_SCANNED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("DEVICE_BARCODE_SCANNED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode scanned.
        /// </summary>
        public static string DEVICE_BARCODE_SCANNED_EVENT_NAME {
            get {
                return ResourceManager.GetString("DEVICE_BARCODE_SCANNED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device related events.
        /// </summary>
        public static string DEVICE_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("DEVICE_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string DEVICE_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("DEVICE_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smartcard reader data event.
        /// </summary>
        public static string DEVICE_SMART_CARD_READER_DATA_EVENT_NAME {
            get {
                return ResourceManager.GetString("DEVICE_SMART_CARD_READER_DATA_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smartcard reader data event.
        /// </summary>
        public static string DEVICE_SMART_CARD_READER_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("DEVICE_SMART_CARD_READER_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates an database entity chgange.
        /// </summary>
        public static string ENTITY_CHANGE_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ENTITY_CHANGE_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity change.
        /// </summary>
        public static string ENTITY_CHANGE_EVENT_NAME {
            get {
                return ResourceManager.GetString("ENTITY_CHANGE_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity related events.
        /// </summary>
        public static string ENTITY_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("ENTITY_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity.
        /// </summary>
        public static string ENTITY_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("ENTITY_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client version changed event.
        /// </summary>
        public static string HOST_COMPUTER_CLIENT_MODULE_VERSION_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_CLIENT_MODULE_VERSION_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client version changed.
        /// </summary>
        public static string HOST_COMPUTER_CLIENT_MODULE_VERSION_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_CLIENT_MODULE_VERSION_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection changed event.
        /// </summary>
        public static string HOST_COMPUTER_CONNECTION_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_CONNECTION_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection changed.
        /// </summary>
        public static string HOST_COMPUTER_CONNECTION_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_CONNECTION_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host computer related events.
        /// </summary>
        public static string HOST_COMPUTER_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host computer.
        /// </summary>
        public static string HOST_COMPUTER_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input lock changed event.
        /// </summary>
        public static string HOST_COMPUTER_INPUT_LOCK_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_INPUT_LOCK_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input lock changed.
        /// </summary>
        public static string HOST_COMPUTER_INPUT_LOCK_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_INPUT_LOCK_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance changed event.
        /// </summary>
        public static string HOST_COMPUTER_MAINTENANCE_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_MAINTENANCE_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance changed.
        /// </summary>
        public static string HOST_COMPUTER_MAINTENANCE_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_MAINTENANCE_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security changed event.
        /// </summary>
        public static string HOST_COMPUTER_SECURITY_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_SECURITY_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security changed.
        /// </summary>
        public static string HOST_COMPUTER_SECURITY_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_COMPUTER_SECURITY_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host related events.
        /// </summary>
        public static string HOST_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string HOST_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("HOST_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host in order state changed.
        /// </summary>
        public static string HOST_IN_ORDER_STATE_CHANED_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_IN_ORDER_STATE_CHANED_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order state changed.
        /// </summary>
        public static string HOST_IN_ORDER_STATE_CHANED_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("HOST_IN_ORDER_STATE_CHANED_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout created event.
        /// </summary>
        public static string HOST_LAYOUT_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout created.
        /// </summary>
        public static string HOST_LAYOUT_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout related events.
        /// </summary>
        public static string HOST_LAYOUT_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout.
        /// </summary>
        public static string HOST_LAYOUT_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout group created event.
        /// </summary>
        public static string HOST_LAYOUT_GROUP_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_GROUP_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout group created.
        /// </summary>
        public static string HOST_LAYOUT_GROUP_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_GROUP_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout group related events.
        /// </summary>
        public static string HOST_LAYOUT_GROUP_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_GROUP_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout group.
        /// </summary>
        public static string HOST_LAYOUT_GROUP_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_GROUP_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout group removed event.
        /// </summary>
        public static string HOST_LAYOUT_GROUP_REMOVED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_GROUP_REMOVED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout group removed.
        /// </summary>
        public static string HOST_LAYOUT_GROUP_REMOVED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_GROUP_REMOVED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout group updated event.
        /// </summary>
        public static string HOST_LAYOUT_GROUP_UPDATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_GROUP_UPDATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout group updated.
        /// </summary>
        public static string HOST_LAYOUT_GROUP_UPDATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_GROUP_UPDATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout removed event.
        /// </summary>
        public static string HOST_LAYOUT_REMOVED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_REMOVED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout removed.
        /// </summary>
        public static string HOST_LAYOUT_REMOVED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_REMOVED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout updated event.
        /// </summary>
        public static string HOST_LAYOUT_UPDATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_UPDATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host layout updated.
        /// </summary>
        public static string HOST_LAYOUT_UPDATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("HOST_LAYOUT_UPDATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host lock state changed.
        /// </summary>
        public static string HOST_LOCK_STATE_CHANED_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_LOCK_STATE_CHANED_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock state changed.
        /// </summary>
        public static string HOST_LOCK_STATE_CHANED_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("HOST_LOCK_STATE_CHANED_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance authentication changed event.
        /// </summary>
        public static string INSTANCE_AUTHENTICATION_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("INSTANCE_AUTHENTICATION_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance authentication changed.
        /// </summary>
        public static string INSTANCE_AUTHENTICATION_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("INSTANCE_AUTHENTICATION_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance authorization changed event.
        /// </summary>
        public static string INSTANCE_AUTHORIZATION_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("INSTANCE_AUTHORIZATION_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance authorization changed.
        /// </summary>
        public static string INSTANCE_AUTHORIZATION_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("INSTANCE_AUTHORIZATION_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance related events.
        /// </summary>
        public static string INSTANCE_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("INSTANCE_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        public static string INSTANCE_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("INSTANCE_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates creation of an invoice.
        /// </summary>
        public static string INVOICE_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("INVOICE_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string INVOICE_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("INVOICE_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice related events.
        /// </summary>
        public static string INVOICE_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("INVOICE_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string INVOICE_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("INVOICE_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates creation of an invoice payment.
        /// </summary>
        public static string INVOICE_PAYMENT_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("INVOICE_PAYMENT_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string INVOICE_PAYMENT_EVENT_NAME {
            get {
                return ResourceManager.GetString("INVOICE_PAYMENT_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License related events.
        /// </summary>
        public static string LICENSE_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LICENSE_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("LICENSE_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is disabled.
        /// </summary>
        public static string LICENSE_STATE_DISABLED_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_STATE_DISABLED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance id is disabled/blocked.
        /// </summary>
        public static string LICENSE_STATE_DISABLED_INSTANCE_ID_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_STATE_DISABLED_INSTANCE_ID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled instance id.
        /// </summary>
        public static string LICENSE_STATE_DISABLED_INSTANCE_ID_NAME {
            get {
                return ResourceManager.GetString("LICENSE_STATE_DISABLED_INSTANCE_ID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string LICENSE_STATE_DISABLED_NAME {
            get {
                return ResourceManager.GetString("LICENSE_STATE_DISABLED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is expired.
        /// </summary>
        public static string LICENSE_STATE_EXPIRED_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_STATE_EXPIRED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string LICENSE_STATE_EXPIRED_NAME {
            get {
                return ResourceManager.GetString("LICENSE_STATE_EXPIRED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local license is invalid.
        /// </summary>
        public static string LICENSE_STATE_INVALID_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_STATE_INVALID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string LICENSE_STATE_INVALID_NAME {
            get {
                return ResourceManager.GetString("LICENSE_STATE_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string LICENSE_STATE_UNAUTHORIZED_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_STATE_UNAUTHORIZED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string LICENSE_STATE_UNAUTHORIZED_NAME {
            get {
                return ResourceManager.GetString("LICENSE_STATE_UNAUTHORIZED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string LICENSE_STATE_VALID_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_STATE_VALID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string LICENSE_STATE_VALID_NAME {
            get {
                return ResourceManager.GetString("LICENSE_STATE_VALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal license.
        /// </summary>
        public static string LICENSE_TYPE_NORMAL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_TYPE_NORMAL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string LICENSE_TYPE_NORMAL_NAME {
            get {
                return ResourceManager.GetString("LICENSE_TYPE_NORMAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial license.
        /// </summary>
        public static string LICENSE_TYPE_TRIAL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_TYPE_TRIAL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string LICENSE_TYPE_TRIAL_NAME {
            get {
                return ResourceManager.GetString("LICENSE_TYPE_TRIAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License type is undetermined.
        /// </summary>
        public static string LICENSE_TYPE_UNDETERMINED_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_TYPE_UNDETERMINED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undetermined.
        /// </summary>
        public static string LICENSE_TYPE_UNDETERMINED_NAME {
            get {
                return ResourceManager.GetString("LICENSE_TYPE_UNDETERMINED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates log being cleared.
        /// </summary>
        public static string LOG_CLEARED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOG_CLEARED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string LOG_CLEARED_EVENT_NAME {
            get {
                return ResourceManager.GetString("LOG_CLEARED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log related events.
        /// </summary>
        public static string LOG_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOG_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LOG_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("LOG_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates options change.
        /// </summary>
        public static string OPTIONS_CHANGE_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTIONS_CHANGE_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string OPTIONS_CHANGE_EVENT_NAME {
            get {
                return ResourceManager.GetString("OPTIONS_CHANGE_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options related events.
        /// </summary>
        public static string OPTIONS_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTIONS_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OPTIONS_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("OPTIONS_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates creation of an order.
        /// </summary>
        public static string ORDER_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ORDER_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ORDER_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("ORDER_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates order delivery status change.
        /// </summary>
        public static string ORDER_DELIVERY_STATUS_CHANGE_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ORDER_DELIVERY_STATUS_CHANGE_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ORDER_DELIVERY_STATUS_CHANGE_EVENT_NAME {
            get {
                return ResourceManager.GetString("ORDER_DELIVERY_STATUS_CHANGE_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order related events.
        /// </summary>
        public static string ORDER_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("ORDER_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string ORDER_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("ORDER_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates order line delivery status change.
        /// </summary>
        public static string ORDER_LINE_DELIVERY_STATUS_CHANGE_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ORDER_LINE_DELIVERY_STATUS_CHANGE_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ORDER_LINE_DELIVERY_STATUS_CHANGE_EVENT_NAME {
            get {
                return ResourceManager.GetString("ORDER_LINE_DELIVERY_STATUS_CHANGE_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates order status change.
        /// </summary>
        public static string ORDER_STATUS_CHANGE_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ORDER_STATUS_CHANGE_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ORDER_STATUS_CHANGE_EVENT_NAME {
            get {
                return ResourceManager.GetString("ORDER_STATUS_CHANGE_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates payment intent completion.
        /// </summary>
        public static string PAYMENT_INTENT_COMPLETED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_COMPLETED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string PAYMENT_INTENT_COMPLETED_EVENT_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_COMPLETED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates payment intent creation.
        /// </summary>
        public static string PAYMENT_INTENT_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string PAYMENT_INTENT_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment intent related events.
        /// </summary>
        public static string PAYMENT_INTENT_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment intent.
        /// </summary>
        public static string PAYMENT_INTENT_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates product stock level change.
        /// </summary>
        public static string PRODUCT_STOCK_CHANGE_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("PRODUCT_STOCK_CHANGE_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string PRODUCT_STOCK_CHANGE_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_STOCK_CHANGE_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product stock related events.
        /// </summary>
        public static string PRODUCT_STOCK_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("PRODUCT_STOCK_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product stock.
        /// </summary>
        public static string PRODUCT_STOCK_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_STOCK_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset added event.
        /// </summary>
        public static string REPORT_PRESET_ADDED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("REPORT_PRESET_ADDED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset added.
        /// </summary>
        public static string REPORT_PRESET_ADDED_EVENT_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_ADDED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string REPORT_PRESET_RANGE_DAY_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_RANGE_DAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string REPORT_PRESET_RANGE_MONTH_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_RANGE_MONTH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string REPORT_PRESET_RANGE_WEEK_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_RANGE_WEEK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string REPORT_PRESET_RANGE_YEAR_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_RANGE_YEAR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset removed event.
        /// </summary>
        public static string REPORT_PRESET_REMOVED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("REPORT_PRESET_REMOVED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset removed.
        /// </summary>
        public static string REPORT_PRESET_REMOVED_EVENT_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_REMOVED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset updated event.
        /// </summary>
        public static string REPORT_PRESET_UPDATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("REPORT_PRESET_UPDATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset updated.
        /// </summary>
        public static string REPORT_PRESET_UPDATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_UPDATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation cancelled.
        /// </summary>
        public static string RESERVATION_CANCELLED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("RESERVATION_CANCELLED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string RESERVATION_CANCELLED_EVENT_NAME {
            get {
                return ResourceManager.GetString("RESERVATION_CANCELLED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation created.
        /// </summary>
        public static string RESERVATION_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("RESERVATION_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string RESERVATION_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("RESERVATION_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation related events.
        /// </summary>
        public static string RESERVATION_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("RESERVATION_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string RESERVATION_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("RESERVATION_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation updated.
        /// </summary>
        public static string RESERVATION_UPDATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("RESERVATION_UPDATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string RESERVATION_UPDATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("RESERVATION_UPDATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates shift end.
        /// </summary>
        public static string SHIFT_ENDED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHIFT_ENDED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string SHIFT_ENDED_EVENT_NAME {
            get {
                return ResourceManager.GetString("SHIFT_ENDED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift releated events.
        /// </summary>
        public static string SHIFT_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHIFT_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string SHIFT_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("SHIFT_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates shift lock.
        /// </summary>
        public static string SHIFT_LOCKED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHIFT_LOCKED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string SHIFT_LOCKED_EVENT_NAME {
            get {
                return ResourceManager.GetString("SHIFT_LOCKED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates shift start.
        /// </summary>
        public static string SHIFT_STARTED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHIFT_STARTED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string SHIFT_STARTED_EVENT_NAME {
            get {
                return ResourceManager.GetString("SHIFT_STARTED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates shift unlock.
        /// </summary>
        public static string SHIFT_UNLOCKED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHIFT_UNLOCKED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        public static string SHIFT_UNLOCKED_EVENT_NAME {
            get {
                return ResourceManager.GetString("SHIFT_UNLOCKED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates enablement of an user.
        /// </summary>
        public static string USER_ENABLED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("USER_ENABLED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string USER_ENABLED_EVENT_NAME {
            get {
                return ResourceManager.GetString("USER_ENABLED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User related events.
        /// </summary>
        public static string USER_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("USER_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string USER_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("USER_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User session created.
        /// </summary>
        public static string USER_SESSION_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("USER_SESSION_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string USER_SESSION_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("USER_SESSION_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User session related events.
        /// </summary>
        public static string USER_SESSION_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("USER_SESSION_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User session.
        /// </summary>
        public static string USER_SESSION_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("USER_SESSION_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User session moved.
        /// </summary>
        public static string USER_SESSION_MOVED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("USER_SESSION_MOVED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved.
        /// </summary>
        public static string USER_SESSION_MOVED_EVENT_NAME {
            get {
                return ResourceManager.GetString("USER_SESSION_MOVED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State changed.
        /// </summary>
        public static string USER_SESSION_STATE_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("USER_SESSION_STATE_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User session state changed.
        /// </summary>
        public static string USER_SESSION_STATE_CHANGED_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("USER_SESSION_STATE_CHANGED_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation changed event.
        /// </summary>
        public static string WAITING_LINE_ESTIMATION_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("WAITING_LINE_ESTIMATION_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation changed.
        /// </summary>
        public static string WAITING_LINE_ESTIMATION_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("WAITING_LINE_ESTIMATION_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting line.
        /// </summary>
        public static string WAITING_LINE_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("WAITING_LINE_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting line related events.
        /// </summary>
        public static string WAITING_LINE_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("WAITING_LINE_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting line timed out event.
        /// </summary>
        public static string WAITING_LINE_TIMED_OUT_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("WAITING_LINE_TIMED_OUT_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out.
        /// </summary>
        public static string WAITING_LINE_TIMED_OUT_EVENT_NAME {
            get {
                return ResourceManager.GetString("WAITING_LINE_TIMED_OUT_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added event.
        /// </summary>
        public static string WAITING_LINE_USER_ADDED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("WAITING_LINE_USER_ADDED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added.
        /// </summary>
        public static string WAITING_LINE_USER_ADDED_EVENT_NAME {
            get {
                return ResourceManager.GetString("WAITING_LINE_USER_ADDED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User moved event.
        /// </summary>
        public static string WAITING_LINE_USER_MOVED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("WAITING_LINE_USER_MOVED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User moved.
        /// </summary>
        public static string WAITING_LINE_USER_MOVED_EVENT_NAME {
            get {
                return ResourceManager.GetString("WAITING_LINE_USER_MOVED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User removed event.
        /// </summary>
        public static string WAITING_LINE_USER_REMOVED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("WAITING_LINE_USER_REMOVED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User removed.
        /// </summary>
        public static string WAITING_LINE_USER_REMOVED_EVENT_NAME {
            get {
                return ResourceManager.GetString("WAITING_LINE_USER_REMOVED_EVENT_NAME", resourceCulture);
            }
        }
    }
}
