//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Web.Api.Models.Autogenerated {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Web.Api.Models.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates assistance request status change.
        /// </summary>
        public static string ASSISTANCE_REQUEST_CHANGE_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_CHANGE_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ASSISTANCE_REQUEST_CHANGE_EVENT_EVENT_NAME {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_CHANGE_EVENT_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates assistance request creation.
        /// </summary>
        public static string ASSISTANCE_REQUEST_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ASSISTANCE_REQUEST_CREATED_EVENT_EVENT_NAME {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_CREATED_EVENT_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance request related events.
        /// </summary>
        public static string ASSISTANCE_REQUEST_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance request.
        /// </summary>
        public static string ASSISTANCE_REQUEST_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("ASSISTANCE_REQUEST_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch created event.
        /// </summary>
        public static string BRANCH_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch created.
        /// </summary>
        public static string BRANCH_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch deleted event.
        /// </summary>
        public static string BRANCH_DELETED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_DELETED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string BRANCH_DELETED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_DELETED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch releated events.
        /// </summary>
        public static string BRANCH_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string BRANCH_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("BRANCH_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator added event.
        /// </summary>
        public static string BRANCH_OPERATOR_ADDED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_ADDED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator added.
        /// </summary>
        public static string BRANCH_OPERATOR_ADDED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_ADDED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators default branch change event.
        /// </summary>
        public static string BRANCH_OPERATOR_DEFAULT_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_DEFAULT_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators default branch change.
        /// </summary>
        public static string BRANCH_OPERATOR_DEFAULT_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_DEFAULT_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator removed event.
        /// </summary>
        public static string BRANCH_OPERATOR_REMOVED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_REMOVED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator removed.
        /// </summary>
        public static string BRANCH_OPERATOR_REMOVED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_OPERATOR_REMOVED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch undeleted event.
        /// </summary>
        public static string BRANCH_UNDELETED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_UNDELETED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeleted.
        /// </summary>
        public static string BRANCH_UNDELETED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_UNDELETED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch updated event.
        /// </summary>
        public static string BRANCH_UPDATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BRANCH_UPDATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch updated.
        /// </summary>
        public static string BRANCH_UPDATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("BRANCH_UPDATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates an database entity chgange.
        /// </summary>
        public static string ENTITY_CHANGE_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ENTITY_CHANGE_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity change.
        /// </summary>
        public static string ENTITY_CHANGE_EVENT_NAME {
            get {
                return ResourceManager.GetString("ENTITY_CHANGE_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity related events.
        /// </summary>
        public static string ENTITY_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("ENTITY_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity.
        /// </summary>
        public static string ENTITY_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("ENTITY_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host related events.
        /// </summary>
        public static string HOST_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string HOST_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("HOST_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License related events.
        /// </summary>
        public static string LICENSE_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LICENSE_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("LICENSE_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates options change.
        /// </summary>
        public static string OPTIONS_CHANGED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTIONS_CHANGED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string OPTIONS_CHANGED_EVENT_NAME {
            get {
                return ResourceManager.GetString("OPTIONS_CHANGED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options related events.
        /// </summary>
        public static string OPTIONS_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("OPTIONS_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OPTIONS_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("OPTIONS_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order related events.
        /// </summary>
        public static string ORDER_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("ORDER_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string ORDER_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("ORDER_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates payment intent completion.
        /// </summary>
        public static string PAYMENT_INTENT_COMPLETED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_COMPLETED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string PAYMENT_INTENT_COMPLETED_EVENT_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_COMPLETED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates payment intent creation.
        /// </summary>
        public static string PAYMENT_INTENT_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string PAYMENT_INTENT_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment intent related events.
        /// </summary>
        public static string PAYMENT_INTENT_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment intent.
        /// </summary>
        public static string PAYMENT_INTENT_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset added event.
        /// </summary>
        public static string REPORT_PRESET_ADDED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("REPORT_PRESET_ADDED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset added.
        /// </summary>
        public static string REPORT_PRESET_ADDED_EVENT_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_ADDED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string REPORT_PRESET_RANGE_DAY_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_RANGE_DAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string REPORT_PRESET_RANGE_MONTH_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_RANGE_MONTH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string REPORT_PRESET_RANGE_WEEK_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_RANGE_WEEK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string REPORT_PRESET_RANGE_YEAR_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_RANGE_YEAR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset removed event.
        /// </summary>
        public static string REPORT_PRESET_REMOVED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("REPORT_PRESET_REMOVED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset removed.
        /// </summary>
        public static string REPORT_PRESET_REMOVED_EVENT_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_REMOVED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset updated event.
        /// </summary>
        public static string REPORT_PRESET_UPDATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("REPORT_PRESET_UPDATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report preset updated.
        /// </summary>
        public static string REPORT_PRESET_UPDATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("REPORT_PRESET_UPDATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation related events.
        /// </summary>
        public static string RESERVATION_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("RESERVATION_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string RESERVATION_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("RESERVATION_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates shift end.
        /// </summary>
        public static string SHIFT_ENDED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHIFT_ENDED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string SHIFT_ENDED_EVENT_NAME {
            get {
                return ResourceManager.GetString("SHIFT_ENDED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift releated events.
        /// </summary>
        public static string SHIFT_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHIFT_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string SHIFT_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("SHIFT_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates shift lock.
        /// </summary>
        public static string SHIFT_LOCKED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHIFT_LOCKED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string SHIFT_LOCKED_EVENT_NAME {
            get {
                return ResourceManager.GetString("SHIFT_LOCKED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates shift start.
        /// </summary>
        public static string SHIFT_STARTED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHIFT_STARTED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string SHIFT_STARTED_EVENT_NAME {
            get {
                return ResourceManager.GetString("SHIFT_STARTED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates shift unlock.
        /// </summary>
        public static string SHIFT_UNLOCKED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHIFT_UNLOCKED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        public static string SHIFT_UNLOCKED_EVENT_NAME {
            get {
                return ResourceManager.GetString("SHIFT_UNLOCKED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates enablement of an user.
        /// </summary>
        public static string USER_ENABLED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("USER_ENABLED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string USER_ENABLED_EVENT_NAME {
            get {
                return ResourceManager.GetString("USER_ENABLED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User related events.
        /// </summary>
        public static string USER_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("USER_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string USER_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("USER_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting line.
        /// </summary>
        public static string WAITING_LINE_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("WAITING_LINE_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting line related events.
        /// </summary>
        public static string WAITING_LINE_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("WAITING_LINE_EVENT_GROUP_NAME", resourceCulture);
            }
        }
    }
}
