using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User achievement challenge completed event message — a challenge completion was
    /// earned and its rewards were created.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Challenge completed", nameof(Resources.ACHIEVEMENT_CHALLENGE_COMPLETED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates user completed an achievement challenge", nameof(Resources.ACHIEVEMENT_CHALLENGE_COMPLETED_EVENT_DESCRIPTION))]
    public sealed class UserAchievementChallengeCompletedEventMessage : UserAchievementEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserAchievementChallengeCompletedEventMessage() : base()
        { }

        /// <summary>
        /// Gets challenge id.
        /// </summary>
        [Key(2)]
        public required int ChallengeId
        {
            get; init;
        }

        /// <summary>
        /// Gets the user's 1-based completion number of the challenge.
        /// </summary>
        [Key(3)]
        public required int Occurrence
        {
            get; init;
        }

        /// <summary>
        /// Gets the 1-based global finisher number across all users.
        /// </summary>
        [Key(4)]
        public required int GlobalOccurrence
        {
            get; init;
        }
    }
}
