using Gizmo.Web.Api.Models;
using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User achievement reward status changed event message — an earned challenge reward
    /// entered a new grant state: awaiting claim at the counter, granted, declined or
    /// re-offered.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Reward status change", nameof(Resources.ACHIEVEMENT_REWARD_STATUS_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates user achievement reward status change", nameof(Resources.ACHIEVEMENT_REWARD_STATUS_EVENT_DESCRIPTION))]
    public sealed class UserAchievementRewardStatusChangedEventMessage : UserAchievementEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserAchievementRewardStatusChangedEventMessage() : base()
        { }

        /// <summary>
        /// Gets challenge id.
        /// </summary>
        [Key(2)]
        public required int ChallengeId
        {
            get; init;
        }

        /// <summary>
        /// Gets challenge completion id.
        /// </summary>
        [Key(3)]
        public required int CompletionId
        {
            get; init;
        }

        /// <summary>
        /// Gets reward id.
        /// </summary>
        [Key(4)]
        public required int RewardId
        {
            get; init;
        }

        /// <summary>
        /// Gets the reward's new grant status.
        /// </summary>
        [Key(5)]
        public required AchievementChallengeRewardStatus Status
        {
            get; init;
        }
    }
}
