using Gizmo.Web.Api.Models;
using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User achievement ladder level changed event message — the evaluation engine moved
    /// the user between ladder levels (live promotion or period-boundary settle). Richer
    /// than the generic user group change: carries the ranks and the transition trigger.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Achievement level change", nameof(Resources.ACHIEVEMENT_LEVEL_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates user achievement ladder level change", nameof(Resources.ACHIEVEMENT_LEVEL_CHANGE_EVENT_DESCRIPTION))]
    public sealed class UserAchievementLevelChangedEventMessage : UserAchievementEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserAchievementLevelChangedEventMessage() : base()
        { }

        /// <summary>
        /// Gets the ladder rank moved from.
        /// </summary>
        [Key(2)]
        public required int FromRank
        {
            get; init;
        }

        /// <summary>
        /// Gets the ladder rank moved to.
        /// </summary>
        [Key(3)]
        public required int ToRank
        {
            get; init;
        }

        /// <summary>
        /// Gets the user group moved from.
        /// </summary>
        [Key(4)]
        public required int FromUserGroupId
        {
            get; init;
        }

        /// <summary>
        /// Gets the user group moved to.
        /// </summary>
        [Key(5)]
        public required int ToUserGroupId
        {
            get; init;
        }

        /// <summary>
        /// Gets what triggered the transition.
        /// </summary>
        [Key(6)]
        public required AchievementLadderEventTrigger Trigger
        {
            get; init;
        }
    }
}
