using Gizmo.Web.Api.Models.Autogenerated;
using MessagePack;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User achievement completed event message — a completion was recorded for the
    /// achievement's current range instance, or its completion count grew.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Achievement completed", nameof(Resources.ACHIEVEMENT_COMPLETED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates user completed an achievement", nameof(Resources.ACHIEVEMENT_COMPLETED_EVENT_DESCRIPTION))]
    public sealed class UserAchievementCompletedEventMessage : UserAchievementEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserAchievementCompletedEventMessage() : base()
        { }

        /// <summary>
        /// Gets achievement id.
        /// </summary>
        [Key(2)]
        public required int AchievementId
        {
            get; init;
        }

        /// <summary>
        /// Gets the completion count within the achievement's current range instance.
        /// </summary>
        [Key(3)]
        public required int Quantity
        {
            get; init;
        }
    }
}
