using Gizmo.Web.Api.Models;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Order created event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Created", nameof(Resources.ORDER_CREATED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates creation of an order", nameof(Resources.ORDER_CREATED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class OrderCreatedEventMessage : OrderEventMessageBase
    {
        /// <summary>
        /// Gets order status.
        /// </summary>
        /// <remarks>
        /// This will be equal to initial order status.<br></br>
        /// Order might be completed or invoiced (accepted) at creation and we wont be sending logical status transitions changes messages.
        /// </remarks>
        [MessagePack.Key(3)]
        public OrderStatus Status { get; init; }
    }
}
