using Gizmo.Web.Api.Models;
using MessagePack;
using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Order status change event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Change", nameof(Resources.ORDER_STATUS_CHANGE_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates order status change", nameof(Resources.ORDER_STATUS_CHANGE_EVENT_DESCRIPTION))]
    [MessagePackObject()]
    public sealed class OrderStatusChangeEventMessage : OrderEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public OrderStatusChangeEventMessage() : base()
        { }

        /// <summary>
        /// Gets new status.
        /// </summary>
        [Key(3)]
        public OrderStatus Status
        {
            get; init;
        }

        /// <summary>
        /// Gets previous status.
        /// </summary>
        [Key(4)]
        public OrderStatus? PreviousStatus
        {
            get; init;
        }
    }
}
