using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Shift ended event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Ended", nameof(Resources.SHIFT_ENDED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates shift end", nameof(Resources.SHIFT_ENDED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class ShiftEndedEventMessage : ShiftEventMessageBase
    {
    }
}
