using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Shift unlocked event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Unlocked", nameof(Resources.SHIFT_UNLOCKED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates shift unlock", nameof(Resources.SHIFT_UNLOCKED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class ShiftUnlockedEventMessage : ShiftEventMessageBase
    {
    }
}
