using Gizmo.Web.Api.Models;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User session created event.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Created", nameof(Resources.USER_SESSION_CREATED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("User session created", nameof(Resources.USER_SESSION_CREATED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class UserSessionCreatedEventMessage : UserSessionEventMessageBase
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserSessionCreatedEventMessage()
        { }

        /// <summary>
        /// Initial session state.
        /// </summary>
        [MessagePack.Key(5)]
        public UserSessionState State
        {
            get; init;
        }
    }
}
