using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Branch created event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Undeleted", nameof(Resources.BRANCH_UNDELETED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Branch undeleted event", nameof(Resources.BRANCH_UNDELETED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class BranchUndeletedEventMessage : BranchEventMessageBase
    {
        /// <inheritdoc/>
        public BranchUndeletedEventMessage() : base() { }
    }
}
