using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Branch created event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Branch created", nameof(Resources.BRANCH_CREATED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Branch created event", nameof(Resources.BRANCH_CREATED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class BranchCreatedEventMessage : BranchEventMessageBase
    {
        /// <inheritdoc/>
        public BranchCreatedEventMessage() : base() { }
    }
}
