using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Branch created event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Deleted", nameof(Resources.BRANCH_DELETED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Branch deleted event", nameof(Resources.BRANCH_DELETED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class BranchDeletedEventMessage : BranchEventMessageBase
    {
        /// <inheritdoc/>
        public BranchDeletedEventMessage() : base() { }
    }
}
