using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Branch updated event message.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Branch updated", nameof(Resources.BRANCH_UPDATED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Branch updated event", nameof(Resources.BRANCH_UPDATED_EVENT_DESCRIPTION))]
    [MessagePack.MessagePackObject()]
    public sealed class BranchUpdatedEventMessage : BranchEventMessageBase
    {
        /// <inheritdoc/>
        public BranchUpdatedEventMessage() : base() { }
    }
}
