using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Action center event message base.
    /// </summary>
    /// <remarks>
    /// Carries no fields of its own. It exists to group the four action center messages under one
    /// event group, and each of them says what it is about: the ones that carry an entry get it
    /// from the entry, and the ones that do not name it themselves.
    /// <para>
    /// There is deliberately no server run identifier here. Entry sequences restart with the
    /// process, but a restart necessarily drops the connection, and the manager re-syncs on every
    /// reconnect and does not process messages until that sync has succeeded, so it can never
    /// compare a sequence against a high water mark from a different run. This holds only while
    /// that remains true, so nothing may reset the store's sequence in process without dropping
    /// connections.
    /// </para>
    /// </remarks>
    [System.ComponentModel.DataAnnotations.Name("Action center", nameof(Resources.ACTION_CENTER_EVENT_GROUP_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Action center related events", nameof(Resources.ACTION_CENTER_EVENT_GROUP_DESCRIPTION))]
    [EventGroup(27)]
    public abstract class ActionCenterEventMessageBase : APIEventMessage
    {
        /// <inheritdoc/>
        public ActionCenterEventMessageBase() : base()
        { }
    }
}
