using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Device event message base.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Device", nameof(Resources.BRANCH_EVENT_GROUP_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Device related events", nameof(Resources.DEVICE_EVENT_GROUP_DESCRIPTION))]
    [EventGroup(21)]
    public abstract class DeviceEventMessageBase : APIEventMessage
    {
        /// <inheritdoc/>
        public DeviceEventMessageBase():base()
        {}
    }
}
