using Gizmo.Web.Api.Messaging;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Models
{
    /// <summary>
    /// Instance event message base.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Instance", nameof(Resources.INSTANCE_EVENT_GROUP_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Instance related events", nameof(Resources.INSTANCE_EVENT_GROUP_DESCRIPTION))]
    [EventGroup(22)]
    public abstract class InstanceEventMessageBase : APIEventMessage
    {
    }
}
