using MessagePack;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Order event message base.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Order", nameof(Resources.ORDER_EVENT_GROUP_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Order related events", nameof(Resources.ORDER_EVENT_GROUP_DESCRIPTION))]
    [HideMetadata()]
    [EventGroup(2)]
    public abstract class OrderEventMessageBase : APIEventMessage
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public OrderEventMessageBase() : base()
        { }

        /// <summary>
        /// Gets order id.
        /// </summary>
        [Key(1)]
        public required int OrderId { get; set; }

        /// <summary>
        /// User id.
        /// </summary>
        [Key(2)]
        public required int UserId { get; init; }
    }
}
