using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Product stock event message base.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Product stock", nameof(Resources.PRODUCT_STOCK_EVENT_GROUP_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Product stock related events", nameof(Resources.PRODUCT_STOCK_EVENT_GROUP_DESCRIPTION))]
    [EventGroup(16)]
    public abstract class ProductStockChangeEventMessageBase : APIEventMessage
    {
        /// <summary>
        /// Gets product id.
        /// </summary>
        [MessagePack.Key(1)]
        public int ProductId
        {
            get; init;
        }

        /// <summary>
        /// Gets stock id.
        /// </summary>
        [MessagePack.Key(2)]
        public int StockId
        {
            get; init; 
        }
    }
}
