using MessagePack;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User achievement event message base.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("Achievement", nameof(Resources.ACHIEVEMENT_EVENT_GROUP_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Achievement related events", nameof(Resources.ACHIEVEMENT_EVENT_GROUP_DESCRIPTION))]
    [EventGroup(26)]
    public abstract class UserAchievementEventMessageBase : APIEventMessage
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        public UserAchievementEventMessageBase() : base()
        { }

        /// <summary>
        /// Gets user id.
        /// </summary>
        [Key(1)]
        public int UserId
        {
            get; set;
        }
    }
}
