using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// User guest event message base.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Name("User guest", nameof(Resources.USER_GUEST_EVENT_GROUP_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("User guest related events", nameof(Resources.USER_GUEST_EVENT_GROUP_DESCRIPTION))]
    [EventGroup(23)]
    public abstract class UserGuestEventMessageBase : APIEventMessage
    {
        /// <inheritdoc/>
        public UserGuestEventMessageBase()
        { }

        /// <summary>
        /// User id.
        /// </summary>
        [MessagePack.Key(1)]
        public int UserId { get; init; }
    }
}
