using MessagePack;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Payment intent failed event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Failed", nameof(Resources.PAYMENT_INTENT_FAILED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates payment intent failure", nameof(Resources.PAYMENT_INTENT_FAILED_EVENT_DESCRIPTION))]
    public sealed class PaymentIntentFailedEventMessage : PaymentIntentEventMessageBase
    {
    }
}
