using MessagePack;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Payment intent state changed.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Completed", nameof(Resources.PAYMENT_INTENT_COMPLETED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates payment intent completion", nameof(Resources.PAYMENT_INTENT_COMPLETED_EVENT_DESCRIPTION))]
    public sealed class PaymentIntentCompletedEventMessage : PaymentIntentEventMessageBase
    {        
    }
}
