using MessagePack;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Payment intent captured event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Cancelled", nameof(Resources.PAYMENT_INTENT_CANCELLED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates payment intent cancellation", nameof(Resources.PAYMENT_INTENT_CANCELLED_EVENT_DESCRIPTION))]
    public sealed class PaymentIntentCancelledEventMessage : PaymentIntentEventMessageBase
    {        
    }
}
