using MessagePack;

using Gizmo.Web.Api.Models.Autogenerated;

namespace Gizmo.Web.Api.Messaging
{
    /// <summary>
    /// Payment intent expiration event message.
    /// </summary>
    [MessagePackObject()]
    [System.ComponentModel.DataAnnotations.Name("Expired", nameof(Resources.PAYMENT_INTENT_EXPIRED_EVENT_NAME))]
    [System.ComponentModel.DataAnnotations.ExtendedDescription("Indicates payment intent expired", nameof(Resources.PAYMENT_INTENT_EXPIRED_EVENT_DESCRIPTION))]
    public sealed class PaymentIntentExpiredEventMessage : PaymentIntentEventMessageBase
    {
    }
}
